waku-org/js-waku

- src/lib/waku_relay.spec.ts
- tsconfig.json
status-im/nim-waku/issues/419 has been fixed.
> Missing protocols in identify message are now present 

- src/test_utils/nim_waku.spec.ts
- src/test_utils/nim_waku.ts
Confirms resolution of https://github.com/status-im/nim-waku/issues/415
> Update nim-waku, `0x` now optional in RPC requests

- .eslintrc.json
- src/chat/index.ts
- src/lib/waku_store/history_rpc.ts
- src/lib/waku_store/index.spec.ts
- src/lib/waku_store/index.ts
> Implement pagination for waku store

- .cspell.json
- package-lock.json
- package.json
- src/chat/index.ts
- src/lib/waku.spec.ts
- src/lib/waku.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_store/index.spec.ts
- src/types/types.d.ts
> Add websocket transport

- src/chat/index.ts
- src/lib/waku.ts
- src/lib/waku_relay/get_relay_peers.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.spec.ts
> Use peerStore event to determine if identify is done & Auto-subscribe

- .github/workflows/ci.yml
- .gitignore
- README.md
- package.json
- src/chat/index.ts
- src/proto/chat/v2/chat_message.ts
- src/proto/waku/v2/message.ts
- src/proto/waku/v2/store.ts
> Improve chat cli setup UX

- .github/workflows/ci.yml
- README.md
- proto/waku/v2/store.proto
- src/lib/waku_store/history_rpc.ts
- src/proto/waku/v2/store.ts
> Update to latest waku store

- package-lock.json
- package.json
- src/proto/chat/v2/chat_message.ts
- src/proto/waku/v2/message.ts
- src/proto/waku/v2/store.ts
> Upgrade ts-proto to fix long dependency warning/error

- src/chat/index.ts
As it seems to fail on some systems
> Log in error raised by question

- README.md
- web-chat/src/App.tsx
- web-chat/src/ChatList.tsx
- web-chat/src/MessageInput.tsx
- web-chat/src/Room.tsx
- web-chat/src/command.ts
- web-chat/src/index.css
> Few UI improvements

- .github/workflows/deploy-gh-pages.yml
- web-chat/package.json
- web-chat/public/index.html
> Use GitHub action to deploy web app

- LICENSE-APACHE-v2
- LICENSE-MIT
- README.md
> Apply MIT or Apache V2.0 License

- web-chat/package-lock.json
- web-chat/package.json
- web-chat/src/App.tsx
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Feature
- **What is the current behavior?** (You can also link to an open issue here)
- Resolves #81
- Default is "web-chat"
- **What is the new behavior (if this is a feature change)?**
- Random name generated if name is "web-chat"
> Use random name for nickname by default

- proto/waku/v2/store.proto
- src/lib/waku_store/history_rpc.ts
- src/lib/waku_store/index.ts
- src/proto/waku/v2/store.ts
> Enable pubsub topic filter in history queries

- web-chat/.cspell.json
- web-chat/package-lock.json
- web-chat/package.json
- web-chat/src/App.tsx
- web-chat/src/ChatList.tsx
- web-chat/src/MessageInput.tsx
- web-chat/src/Room.tsx
- web-chat/src/types/types.d.ts
- web-chat/tsconfig.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Refactor
- **What is the current behavior?** (You can also link to an open issue here)
Custom React Material UI Implementation
- **What is the new behavior (if this is a feature change)?**
Off the shelf React Material Chat UI Implementation
> Use off-the-shelf React Templates for UI

- web-chat/package-lock.json
- web-chat/package.json
- web-chat/src/App.tsx
- web-chat/src/ChatList.tsx
- web-chat/src/MessageInput.tsx
> Use waku store to retrieve archived messages in browser app

- README.md
> No need to change Firefox for the web app

- .github/workflows/examples-ci.yml
- .mocharc.json
- README.md
- bors.toml
- examples/cli-chat/.eslintrc.json
- examples/cli-chat/.gitignore
- examples/cli-chat/.mocharc.json
- examples/cli-chat/README.md
- examples/cli-chat/package-lock.json
- examples/cli-chat/package.json
- examples/cli-chat/src/chat.spec.ts
- examples/cli-chat/src/chat.ts
- examples/cli-chat/src/index.ts
- examples/cli-chat/src/types/types.d.ts
- examples/cli-chat/tsconfig.json
- package-lock.json
- package.json
- src/chat/index.ts
- src/lib/chat_message/index.spec.ts
- src/lib/chat_message/index.ts
- web-chat/package-lock.json
- web-chat/package.json
- web-chat/src/App.tsx
- web-chat/src/ChatList.tsx
- web-chat/src/Room.tsx
> Move cli chat to examples folder

- web-chat/src/App.tsx
- web-chat/src/ChatList.tsx
- web-chat/src/ChatMessage.ts
- web-chat/src/MessageInput.tsx
- web-chat/src/Room.tsx
- web-chat/src/command.ts
this removes the `Reached max listeners` error.
> Ensure that listeners are added only when waku is initialised

- examples/web-chat/src/App.tsx
To avoid websocket timeout issue
Resolves #123 (long term solutions are tracked in separate issues)
> Connect directly to websockify

- examples/web-chat/src/App.tsx
- src/lib/waku_store/index.ts
> Log more around usage of waku store + connect to second node

- examples/cli-chat/src/chat.ts
- examples/web-chat/src/App.tsx
- src/lib/waku_message.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/history_rpc.ts
- src/test_utils/nim_waku.ts
> Provide API to process waku messages over relay

- .github/workflows/ci.yml
- src/lib/waku_relay/index.spec.ts
- src/test_utils/nim_waku.ts
> Add debug statement in tests

- .eslintrc.json
- CHANGELOG.md
- examples/cli-chat/package-lock.json
- examples/cli-chat/package.json
- examples/cli-chat/src/chat.spec.ts
- examples/cli-chat/src/chat.ts
- examples/web-chat/package-lock.json
- examples/web-chat/package.json
- examples/web-chat/src/App.tsx
- examples/web-chat/src/ChatList.tsx
- examples/web-chat/src/Room.tsx
- examples/web-chat/src/WakuContext.ts
- examples/web-chat/src/command.ts
- package.json
- src/lib/waku_relay/constants.ts
- tsconfig.dev.json
- tsconfig.json
- tsconfig.module.json
- Test out tarball generated with `npm pack`
- Change name to `web3-waku`
- Introduce changelog file
- Ensure test files are not included in the package
> Prepare for publishing

- .github/workflows/add-action-project.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/examples-ci.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- examples/cli-chat/README.md
- examples/cli-chat/package-lock.json
- examples/cli-chat/package.json
- examples/cli-chat/src/chat.spec.ts
- examples/cli-chat/src/chat.ts
- examples/web-chat/README.md
- examples/web-chat/package-lock.json
- examples/web-chat/package.json
- examples/web-chat/public/index.html
- examples/web-chat/public/manifest.json
- examples/web-chat/src/App.tsx
- examples/web-chat/src/ChatList.tsx
- examples/web-chat/src/Room.tsx
- examples/web-chat/src/WakuContext.ts
- examples/web-chat/src/command.ts
- package-lock.json
- package.json
- src/test_utils/index.ts
To align with go-waku and nim-waku and keep bors working.
> Revert naming to js-waku across the board

- CHANGELOG.md
- examples/web-chat/src/MessageInput.tsx
- src/lib/waku_relay/constants.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/history_rpc.ts
- src/test_utils/nim_waku.ts
- `WakuRelay.getPeers` method.
- Use `WakuRelay.getPeers` in web chat app example to disable send button.
> Add `WakuRelay.getPeers` method

- CHANGELOG.md
- README.md
- examples/cli-chat/src/chat.ts
- examples/web-chat/src/App.tsx
- package-lock.json
- package.json
- src/index.ts
- src/lib/discover.ts
> Add `getStatusFleetNodes` to connect to Status' nim-waku nodes

- CHANGELOG.md
- package.json
Only used for testing purposes.
> Upgrade nim-waku to v0.3

- .github/workflows/ci.yml
As per https://github.com/actions/checkout/issues/417#issuecomment-775293723
> Fix actions/checkout@v2.3.3

- .cspell.json
- CHANGELOG.md
- README.md
- examples/cli-chat/src/chat.ts
- examples/web-chat/src/App.tsx
- proto/waku/v2/light_push.proto
- src/index.ts
- src/lib/waku.ts
- src/lib/waku_light_push/index.spec.ts
- src/lib/waku_light_push/index.ts
- src/lib/waku_light_push/push_rpc.ts
- src/lib/waku_store/index.ts
- src/proto/waku/v2/light_push.ts
- src/test_utils/nim_waku.ts
> Implement Light Push protocol

- src/lib/waku_relay/index.spec.ts
Indeed, the beforeEach/afterEach methods are called for all tests in the
block, including interop tests.
> Ensure that no unnecessary js node are started for interop tests

- .cspell.json
- README.md
- examples/cli-chat/src/chat.ts
- examples/web-chat/src/App.tsx
> Update chat content topic to new testnet value

- README.md
- examples/cli-chat/src/chat.ts
- examples/web-chat/src/App.tsx
As per https://github.com/status-im/nim-waku/pull/583
> Update toy-chat content topic

- CHANGELOG.md
- examples/web-chat/src/App.tsx
> Persist nick

- examples/web-chat/src/App.tsx
> Split useEffect calls

- CHANGELOG.md
- examples/web-chat/src/Message.ts
- examples/web-chat/src/MessageInput.tsx
- src/lib/waku_light_push/index.ts
> Upgrade nim-waku to v0.4

- CHANGELOG.md
- src/lib/waku.ts
Using libp2p ping protocol.
Helps with #185.
> Add keep alive feature

- CHANGELOG.md
- examples/eth-dm/package-lock.json
- examples/eth-dm/package.json
- examples/eth-dm/src/App.tsx
- examples/eth-dm/src/BroadcastPublicKey.tsx
- examples/eth-dm/src/InitWaku.tsx
- examples/eth-dm/src/crypto.ts
- examples/eth-dm/src/messaging/wire.ts
- src/lib/waku.ts
> Replace JSON with Protobuf

- CHANGELOG.md
- examples/eth-dm/src/App.tsx
- examples/eth-dm/src/InitWaku.tsx
- examples/eth-dm/src/crypto.ts
- examples/eth-dm/src/messaging/wire.ts
- examples/eth-dm/src/utils.ts
- src/lib/waku.ts
- src/lib/waku_relay/index.ts
> Eth-DM Clean-ups

- CHANGELOG.md
- src/lib/select_peer.ts
- src/lib/waku_light_push/index.ts
- src/lib/waku_store/index.spec.ts
- src/lib/waku_store/index.ts
> Decrypt messages retrieved from Waku store

- CHANGELOG.md
- examples/eth-dm/package-lock.json
- examples/eth-dm/package.json
- examples/eth-dm/src/App.tsx
- examples/eth-dm/src/BroadcastPublicKey.tsx
- examples/eth-dm/src/crypto.ts
- examples/eth-dm/src/messaging/SendMessage.tsx
- examples/eth-dm/src/messaging/wire.ts
- examples/eth-dm/src/waku.ts
- src/lib/utils.ts
- src/lib/waku_message/index.ts
- src/lib/waku_message/version_1.ts
> Use WakuMessage version 1 instead of eth-crypto for eth-dm

- CHANGELOG.md
- README.md
- examples/eth-dm/src/App.tsx
- examples/eth-dm/src/crypto.ts
- examples/web-chat/src/App.tsx
- examples/web-chat/src/Room.tsx
- examples/web-chat/src/command.ts
- src/index.ts
- src/lib/waku.ts
- src/lib/waku_message/index.spec.ts
- src/lib/waku_relay/index.ts
See patches or CHANGELOG changes for details.
> Several documentation improvement from 0.8.0 release

- CHANGELOG.md
- src/index.ts
- src/lib/waku.spec.ts
- src/lib/waku.ts
- src/lib/waku_relay/constants.ts
- src/lib/waku_relay/get_relay_peers.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.ts
Resolves #238.
Allows compatibility with latest nim-waku release v0.4 + nim-waku master branch.
Tested by confirm relay works on the test fleet using web-chat app.
> Support multiple protocols for Relay

- CHANGELOG.md
- proto/waku/v2/store.proto
- src/lib/waku.spec.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_store/index.ts
- src/proto/waku/v2/store.ts
- src/test_utils/nim_waku.ts
See https://github.com/status-im/nim-waku/releases/tag/v0.5
> Compatibility with nim-waku v0.5

- CHANGELOG.md
- README.md
- examples/cli-chat/src/chat.ts
- examples/eth-dm/src/BroadcastPublicKey.tsx
- examples/eth-dm/src/messaging/SendMessage.tsx
- examples/web-chat/src/App.tsx
- examples/web-chat/src/Room.tsx
- examples/web-chat/src/command.ts
- src/lib/waku.ts
- src/lib/waku_light_push/index.spec.ts
- src/lib/waku_message/index.browser.spec.ts
- src/lib/waku_message/index.spec.ts
- src/lib/waku_message/index.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_store/index.spec.ts
> Remove default content topic

- examples/eth-dm/package.json
- examples/web-chat/package.json
- package.json
- src/test_utils/nim_waku.ts
Parallel tests create issues in GitHub CI: https://github.com/status-im/js-waku/pull/251/checks?check_run_id=3237186978
> Revert "Run tests in parallel"

- examples/eth-dm/src/App.tsx
- examples/eth-dm/src/BroadcastPublicKey.tsx
- examples/eth-dm/src/ConnectWallet.tsx
- examples/eth-dm/src/crypto.ts
- examples/eth-dm/src/key_pair_handling/KeyPairHandling.tsx
- examples/eth-dm/src/key_pair_handling/LoadKeyPair.tsx
- examples/eth-dm/src/key_pair_handling/SaveKeyPair.tsx
- examples/eth-dm/src/key_pair_handling/key_pair_storage.ts
- examples/eth-dm/src/messaging/Messaging.tsx
- examples/eth-dm/src/messaging/SendMessage.tsx
- examples/eth-dm/src/messaging/wire.ts
- examples/eth-dm/src/waku.ts
Do some clean-up in preparation of copying the code to do a version that uses metamask encryption method
> Eth-DM clean-up

- CHANGELOG.md
- examples/eth-pm/package-lock.json
- proto/waku/v2/light_push.proto
- proto/waku/v2/store.proto
- src/index.ts
- src/lib/waku.ts
- src/lib/waku_light_push/index.spec.ts
- src/lib/waku_light_push/index.ts
- src/lib/waku_light_push/push_rpc.ts
- src/lib/waku_relay/constants.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/history_rpc.ts
- src/lib/waku_store/index.spec.ts
- src/lib/waku_store/index.ts
- src/proto/waku/v2/light_push.ts
- src/proto/waku/v2/store.ts
- src/test_utils/nim_waku.ts
>  Moved `DefaultPubSubTopic` to `waku.ts` and fixed the casing

- .cspell.json
- CHANGELOG.md
- guides/encrypt-messages-version-1.md
- guides/menu.md
> Add guide to encrypt messages using version 1

- CHANGELOG.md
- README.md
- guides/encrypt-messages-version-1.md
- src/index.ts
- src/lib/waku.spec.ts
- src/lib/waku.ts
- src/lib/waku_message/index.spec.ts
- src/lib/waku_message/symmetric/browser.ts
- src/lib/waku_message/symmetric/index.ts
- src/lib/waku_message/symmetric/node.ts
- src/lib/waku_message/version_1.ts
- src/lib/waku_relay/index.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.spec.ts
- src/lib/waku_store/index.ts
> Improve encryption API

- examples/examples.md
- examples/store-reactjs-chat/README.md
- examples/store-reactjs-chat/src/App.js
- guides/reactjs-relay.md
- guides/reactjs-store.md
- guides/store-retrieve-messages.md
> New ReactJS Waku Store guide

- examples/min-react-js-chat/README.md
- examples/min-react-js-chat/src/App.js
- examples/store-reactjs-chat/README.md
- guides/reactjs-relay.md
Useful for those using ClojureScript.
Resolves #182.
> Examples with no async/await syntax

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/discovery.browser.spec.ts
- src/lib/discovery.ts
- **hot fix**: Connects to a limited number of bootstrap nodes, defaults to 1.
> Release 0.12.1

- src/lib/waku_relay/relay_heartbeat.ts
https://github.com/ChainSafe/js-libp2p-gossipsub/pull/166/commits/807bf282c5289252e9181109ef109ba2d367ff72
> Fix hearbeat tick handler rounding issue

- package-lock.json
- package.json
Needed to use markdown plugin in docs website.
> Update typedoc deps

- CHANGELOG.md
- src/index.ts
- src/lib/waku_store/index.ts
- src/proto/index.ts
Missed some warnings due to latest update of typedoc.
> doc: Remove warnings

- karma.conf.js
As we have some fast-check tests.
> Increase Karma default timeout for mocha

- .github/workflows/deploy-gh-pages.yml
As it is needed for #377 to have effect.
> Refresh GH pages cache

- .github/workflows/ci.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/examples-ci.yml
- CHANGELOG.md
- package-lock.json
- package.json
A number of libp2p packages do not support node 14 anymore.
> Make minimum support node version 16

- .github/workflows/automerge.yml
https://github.com/marketplace/actions/merge-pull-requests-automerge-action
> Setup automerge action

- src/lib/discovery/bootstrap.ts
- src/lib/discovery/dns.spec.ts
- src/lib/enr/enr.spec.ts
- src/lib/enr/enr.ts
- src/lib/enr/keypair/index.ts
After testing against the new domain name.
> Fix DNS Discovery

- CHANGELOG.md
- examples/relay-reactjs-chat/src/App.js
- examples/store-reactjs-chat/src/App.js
- examples/web-chat/src/App.tsx
- src/lib/waku.node.spec.ts
- src/lib/waku.ts
- src/lib/waku_light_push/index.node.spec.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_relay/index.node.spec.ts
- src/lib/waku_store/index.node.spec.ts
> Replace `waitForConnectedPeer` with `waitForRemotePeer`

- src/lib/waku.node.spec.ts
- src/lib/waku.ts
- src/lib/waku_light_push/index.node.spec.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_relay/index.node.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.node.spec.ts
- src/test_utils/nim_waku.ts
> Wait for heartbeat before considering relay peer ready

- karma.conf.js
- package-lock.json
- package.json
- src/lib/discovery/dns.spec.ts
- src/lib/waku.node.spec.ts
- src/lib/waku.spec.ts
> Do not run bootstrap live data test as part of normal CI

- .mocharc.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/discovery/hosted_json.ts
- src/lib/discovery/index.spec.ts
- src/test_utils/nim_waku.ts
> Remove axios

- CHANGELOG.md
- examples/eth-pm-wallet-encryption/src/crypto.ts
- examples/eth-pm-wallet-encryption/src/messaging/SendMessage.tsx
- examples/eth-pm-wallet-encryption/src/waku.ts
- examples/eth-pm/src/crypto.ts
- examples/eth-pm/src/key_pair_handling/key_pair_storage.ts
- examples/eth-pm/src/messaging/SendMessage.tsx
- examples/eth-pm/src/waku.ts
- src/lib/enr/create.ts
- src/lib/enr/enr.spec.ts
- src/lib/utils.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_message/version_1.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.ts
- src/test_utils/index.ts
- src/test_utils/nim_waku.node.spec.ts
- src/test_utils/nim_waku.ts
- src/test_utils/utf8.ts
Start removing the usage of `Buffer` from the codebase to remove the buffer polyfil.
This work will take several PRs as some crypto dependencies will also need to be removed.
Works towards #337
> Reduce buffer usage

- .mocharc.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/index.ts
- src/lib/discovery/dns.spec.ts
- src/lib/discovery/enrtree.ts
- src/lib/discovery/index.spec.ts
- src/lib/enr/create.ts
- src/lib/enr/enr.spec.ts
- src/lib/enr/enr.ts
- src/lib/enr/keypair/index.ts
- src/lib/enr/keypair/secp256k1.ts
- src/lib/enr/keypair/types.ts
- src/lib/enr/multiaddrs_codec.spec.ts
- src/lib/enr/multiaddrs_codec.ts
- src/lib/enr/v4.ts
- src/lib/utf8.ts
- src/lib/utils.ts
- src/lib/waku.spec.ts
- src/lib/waku_message/index.node.spec.ts
- src/test_utils/index.ts
- src/test_utils/nim_waku.ts
Start removing the usage of `Buffer` from the codebase to remove the buffer polyfil.
This work will take several PRs as some crypto dependencies will also need to be removed.
Works towards #337
> Reduce Buffer usage in ENR module

- bors.toml
https://bors.tech/ to automatically rebase and merge PRs.
> Setup bors

- .github/dependabot.yml
> Ignore patches and minor updates for examples/Add dependabot to angular-relay-chat

- examples/web-chat/src/Room.tsx
Active relay peers are peer which are part of the gossip mesh.
Which means that it's not just a peer we are connect to but a peer on
subscribed to the same pubsub topic, with a good score, part of the
mesh, etc.
Mesh maintenance is done during the gossipsub hearbeat so it's the best
time to review the count.
A store peer is any peer we are connected to that support the store
protocol, so it can be counted when a new peer is added to the store.
This does not cater for store peers that disconnect, but we are not
handling those just yet.
> Improve count of relay peers

- .husky/pre-commit
- .prettierignore
- package-lock.json
- package.json
Make life easier by not having to think about running prettier.
> Add git hook to format and lint staged files

- package.json
We need the hook to fix things when possible.
> Get eslint to fix files in precommit git hook

- CHANGELOG.md
- proto/waku/v2/store/v2beta4/store.proto
- src/proto/waku/v2/store/v2beta4/store.ts
> New `pubsub_topic` field on the `cursor` of Waku Store queries

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/crypto.ts
- src/lib/waku_message/ecies.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_message/index.ts
- src/lib/waku_message/version_1.ts
- src/lib/waku_relay/index.node.spec.ts
> Remove ecies-geth

- src/index.ts
So it can be easily used with `waitForRemotePeer`.
> Export protocols

- CHANGELOG.md
- examples/relay-reactjs-chat/package.json
- package-lock.json
- src/lib/waku.ts
- src/lib/waku_light_push/index.ts
- src/lib/waku_store/index.ts
As it was implicitly using it-pipe@1.0.0 that has a different import
format.
> Declare it-pipe dependency, properly import

- .github/dependabot.yml
It can race condition with bors. Let bors merge handle the
rebasing.
> Stop dependabot's auto rebase

- CHANGELOG.md
- proto/waku/v2/filter.proto
- src/lib/waku.node.spec.ts
- src/lib/waku.ts
- src/lib/waku_filter/filter_rpc.ts
- src/lib/waku_filter/index.node.spec.ts
- src/lib/waku_filter/index.ts
- src/proto/waku/v2/filter.ts
- src/test_utils/nwaku.ts
Supersedes/based on #711 (I did not have push right on `xmtp` branch)
> Implement Waku Filter protocol

- .cspell.json
- src/lib/waku.ts
Resolves https://github.com/status-im/js-waku/issues/766
> Clear all timers on `Waku.stop`

- .github/CODEOWNERS
- .github/dependabot.yml
d4nte is moving to fryorcraken account.
> fix: update GitHub user

- .gitignore
- package-lock.json
- package.json
> fix: remove nyc

- .size-limit.cjs
- CHANGELOG.md
- karma.conf.cjs
- package-lock.json
- package.json
> Remove buffer transient dependency

- bors.toml
This reverts commit 6e6c956af5453b1e55df64f95fd0049dcd197c8b.
> Revert "chore: add `size` task to bors"

- package-lock.json
- package.json
- src/lib/waku_filter/index.ts
> chore(deps): upgrade libp2p

- CHANGELOG.md
- package-lock.json
- package.json
- Simple connection management that selects the most recent connection for store, light push and filter requests.
- **breaking**: `DecryptionParams` may be passed when using `queryHistory` instead of just keys.
- Examples have been moved to https://github.com/waku-org/js-waku-examples.
- doc: add missing modules.
> Release 0.26.0

- .size-limit.cjs
- CHANGELOG.md
- package-lock.json
- package.json
- src/index.ts
- src/lib/create_waku.ts
- src/lib/enr/enr.node.spec.ts
- src/lib/interfaces.ts
- src/lib/wait_for_remote_peer.node.spec.ts
- src/lib/wait_for_remote_peer.ts
- src/lib/waku.node.spec.ts
- src/lib/waku.spec.ts
- src/lib/waku.ts
- src/lib/waku_filter/index.node.spec.ts
- src/lib/waku_light_push/index.node.spec.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_relay/index.node.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.node.spec.ts
- typedoc.json
> feat: createLightNode and createPrivacyNode helpers

- CHANGELOG.md
- README.md
- ci/README.md
- ci/deploy.js
- package.json
Resolves: https://github.com/waku-org/js-waku/issues/943
> ci: update site domain to js.waku.org

- CHANGELOG.md
- src/lib/waku_light_push/index.node.spec.ts
- src/lib/waku_message/index.node.spec.ts
- src/lib/waku_relay/index.node.spec.ts
- src/lib/waku_store/index.node.spec.ts
- src/test_utils/nwaku.ts
Ref: https://github.com/status-im/nwaku/issues/1139
> test: fix typing of JSON RPC response

- CHANGELOG.md
- package.json
Ref: https://github.com/libp2p/js-libp2p-mplex/pull/213#issuecomment-1243219007
> fix: util polyfill not needed

- CHANGELOG.md
- package-lock.json
- package.json
Ref: https://github.com/libp2p/js-libp2p-mplex/issues/215
> fix: downgrade @libp2p/mplex

- CHANGELOG.md
- package-lock.json
- package.json
This reverts commit 4755f2896985b3405404658aef5dc4e73ec10b1b.
Actually a nwaku issue: https://github.com/status-im/nwaku/issues/1085#issuecomment-1244830783
> Revert "fix: downgrade @libp2p/mplex"

- CHANGELOG.md
- buf.gen.yaml
- buf.yaml
- package.json
- rollup.config.js
- src/index.ts
- src/lib/interfaces.ts
- src/lib/waku_filter/index.node.spec.ts
- src/lib/waku_filter/index.ts
- src/lib/waku_light_push/index.node.spec.ts
- src/lib/waku_light_push/index.ts
- src/lib/waku_message/topic_only_message.ts
- src/lib/waku_message/version_0.ts
- src/lib/waku_message/version_1.ts
- src/lib/waku_relay/index.node.spec.ts
- src/lib/waku_relay/index.ts
- src/lib/waku_store/index.node.spec.ts
- src/lib/waku_store/index.ts
- src/proto/message_topic_only.ts
- src/proto/topic_only_message.proto
- src/proto/topic_only_message.ts
- typedoc.json
> Follow-up for #935

- package-lock.json
- package.json
This fixes #920 
I upgraded the Typescript version to version 4.6.3 as suggested by @fryorcraken 
- Resolves #920 
> chore: upgrade typescript version to 4.6.3

- .github/workflows/ci.yml
- .github/workflows/size-limit.yml
- package-lock.json
- package.json
- packages/core/README.md
- packages/core/package.json
New strategy: automatically release from master.
> chore: setup auto-release

- packages/byte-utils/package.json
- packages/core/package.json
- packages/create/package.json
- packages/dns-discovery/package.json
- packages/enr/package.json
- packages/interfaces/package.json
- packages/message-encryption/package.json
> chore: remove unneeded `release` script

- package-lock.json
- packages/core/package.json
- packages/interfaces/package.json
> chore(interfaces/core): bump libp2p to 0.39.5

- .github/workflows/ci.yml
To pick up any upcoming issue.
> test: run CI against nwaku origin/master

- .github/workflows/ci.yml
- packages/core/src/lib/waku.ts
- packages/core/src/lib/waku_store/index.ts
- packages/tests/package.json
- packages/tests/src/nwaku.ts
- packages/tests/tests/nwaku.node.spec.ts
- packages/tests/tests/store.node.spec.ts
- packages/tests/tests/wait_for_remote_peer.node.spec.ts
- packages/tests/tests/waku.node.spec.ts
- issue discovered: https://github.com/status-im/nwaku/issues/1085
> chore(ci/tests): bump nwaku to v0.13.0

- ci/Jenkinsfile
- package.json
- packages/core/package.json
Broken by: https://github.com/waku-org/js-waku/commit/b975943e
> chore: fix builds broken by moving to packages/core

- packages/tests/tests/ephemeral.node.spec.ts
This PR reverts the timeout on a test's `beforeEach` left changed
> fix: revert timeout on test

- .github/workflows/dependabot.yml
Ref: https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027
> chore: attempt to enable dependabot for monorepo

- packages/peer-exchange/src/waku_peer_exchange_discovery.ts
when the query is set in an interval, it first gets invoked when the interval time duration is reached.
refactor: invoke it immediately, and then set/start an interval
> fix: invoke peer exchange query immediately

- packages/core/CHANGELOG.md
- packages/message-encryption/CHANGELOG.md
This is just update to CHANGELOG files after this PR #1111
> chore: update changelog

- .github/workflows/ci.yml
- package.json
- packages/interfaces/package.json
- packages/tests/package.json
- packages/tests/src/nwaku.ts
Extracted from #1128 and would make sense to merge now. See patches for details.
> chore: few test harness improvements

- package-lock.json
- package.json
> chore: remove semantic-release

- .github/workflows/ci.yml
- packages/tests/src/nwaku.ts
- packages/tests/tests/light_push.node.spec.ts
- packages/tests/tests/relay.node.spec.ts
> test: bump nwaku from v0.13.0 to v0.15.0

- package-lock.json
- packages/core/package.json
- packages/core/rollup.config.js
- packages/core/src/lib/base_protocol.ts
- packages/core/src/lib/filter/index.ts
- packages/core/src/lib/light_push/index.ts
- packages/core/src/lib/store/index.ts
- packages/peer-exchange/package.json
- packages/peer-exchange/src/waku_peer_exchange.ts
Ref: https://github.com/waku-org/js-waku/pull/1137
> chore: use `BaseProtocol` on `WakuPeerExchange`

- .size-limit.cjs
- packages/core/src/index.ts
- packages/message-encryption/src/decoded_message.ts
- packages/message-encryption/src/ecies.ts
- packages/message-encryption/src/index.ts
- packages/message-encryption/src/symmetric.ts
- packages/tests/tests/store.node.spec.ts
> feat: export `Decoder`, `Encoder` and `DecodedMessage` types from root

- packages/core/src/lib/relay/index.ts
- packages/core/src/lib/relay/message_validator.spec.ts
- packages/core/src/lib/relay/message_validator.ts
> feat(relay): validate waku message at gossip layer

- packages/core/src/lib/message/topic_only_message.ts
- packages/core/src/lib/message/version_0.spec.ts
- packages/core/src/lib/message/version_0.ts
- packages/core/src/lib/to_proto_message.ts
- packages/interfaces/src/message.ts
- packages/message-encryption/src/ecies.spec.ts
- packages/message-encryption/src/ecies.ts
- packages/message-encryption/src/symmetric.spec.ts
- packages/message-encryption/src/symmetric.ts
- packages/proto/src/lib/filter.ts
- packages/proto/src/lib/light_push.ts
- packages/proto/src/lib/message.proto
- packages/proto/src/lib/message.ts
- packages/proto/src/lib/store.ts
Ref: https://github.com/waku-org/js-waku/issues/1208
> feat!: enable encoding of meta field

- README.md
- packages/core/README.md
> chore: fix build badge

- packages/core/package.json
- packages/create/package.json
- packages/interfaces/package.json
- packages/proto/package.json
- packages/utils/package.json
Also remove superfluous GLOB in other packages.
> fix(utils): include all ts files

- package-lock.json
- release-please-config.json
`release-please` got confused after manual bump of `@waku/core` and put changes to the log since the bootstrap commit.
Move bootstrap commit to the recent release.
> fix: change bootstrap commit

- .release-please-manifest.json
New relay package is not tracked by release please.
Add it to the manifest.
> chore: add relay to manifest

- packages/core/src/lib/connection_manager.ts
- packages/dns-discovery/src/index.ts
- packages/interfaces/src/connection_manager.ts
- packages/sdk/src/create.ts
- packages/tests/tests/dns-peer-discovery.spec.ts
This PR addresses point 1 at https://github.com/waku-org/js-waku/issues/1326
> feat: allow passing of multiple ENR URLs to DNS Discovery & dial multiple peers in parallel

- packages/tests/tests/store/page_size.node.spec.ts
- packages/tests/tests/store/time_filter.node.spec.ts
Updated the tests to reflect recent gowaku fixes: https://github.com/waku-org/go-waku/pull/800
> fix: gowaku store bugfixes

- package-lock.json
- packages/interfaces/src/libp2p.ts
- packages/interfaces/src/protocols.ts
- packages/sdk/src/create.ts
- packages/tests/tests/create.optional.spec.ts
Consumers spend time investigating `WebScoket` connection failures in console.
As it is not possible to remove them as they are logged by Browser - add info message so that people are aware of such a thing.
- Resolves #1665
> chore: add info message with expected WebSocket connection failures 

- package-lock.json
- packages/message-encryption/package.json
- packages/message-encryption/src/decoded_message.ts
- packages/message-encryption/src/ecies.spec.ts
- packages/message-encryption/src/symmetric.spec.ts
To enable comparison with expected public key
> feat: new `verifySignature`

- packages/tests/tests/filter/single_node/multiple_pubsub.node.spec.ts
- packages/tests/tests/filter/single_node/ping.node.spec.ts
- packages/tests/tests/filter/single_node/push.node.spec.ts
- packages/tests/tests/filter/single_node/subscribe.node.spec.ts
- packages/tests/tests/filter/single_node/unsubscribe.node.spec.ts
- packages/tests/tests/light-push/single_node/index.node.spec.ts
- packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts
> chore: move filter and lightpush tests to a subdir

- packages/utils/src/common/sharding.spec.ts
Algorithm for determining shards needs to be tested against common vectors.
Adds tests for each case added to the RFC
- Related to https://github.com/vacp2p/rfc/pull/664/files
> chore: add autosharding test vectors

- .github/workflows/ci.yml
- packages/tests/src/lib/service_node.ts
- packages/tests/src/run-tests.js
> chore: upgrade nwaku to v0.25

- .release-please-manifest.json
Set proper version of the package.
> chore: set release version of ReactNative pollyfills

- .release-please-manifest.json
- release-please-config.json
Easy fix doesn't work. Let's resort to proper one 
Follow up to https://github.com/waku-org/js-waku/pull/1941
> chore: force release version

- package-lock.json
- packages/sdk/package.json
- packages/sdk/rollup.config.js
`process` is not defined in rollup artifacts
adjust build system
> fix: make rollup replace env var

- .release-please-manifest.json
- release-please-config.json
Once release is done we don't need to force release version.
> chore: remove forced version config

- packages/discovery/src/local-peer-cache/index.ts
Duplicate of https://github.com/waku-org/js-waku/pull/1954
> fix: add try catch to local store

- .husky/pre-commit
- package.json
Husky got updated 
Follow warnings and fix
> chore: update husky to new api

- .github/workflows/add-action-project.yml
> chore: update add-action-project.yml

- .github/CODEOWNERS
Update CODEOWNERS to reference correct team.
> chore: Update CODEOWNERS to reference correct team

- package-lock.json
- packages/sds/.mocha.reporters.json
- packages/sds/.mocharc.cjs
- packages/sds/package.json
SDS continues to use JSON reporting instead of Allure
Shift SDS to use Allure
> chore(sds): use allure reporting

- .github/workflows/ci.yml
- .github/workflows/test-node.yml
- packages/tests/.mocharc.cjs
- packages/tests/src/lib/dockerode.ts
- packages/tests/src/lib/index.ts
- packages/tests/src/lib/service_node.ts
- packages/tests/src/run-tests.js
- packages/tests/src/sync-rln-tree.js
- packages/tests/src/utils/nodes.ts
- packages/tests/src/utils/teardown.ts
- packages/tests/tests/dns-peer-discovery.spec.ts
- packages/tests/tests/ephemeral.node.spec.ts
- packages/tests/tests/filter/subscribe.node.spec.ts
- packages/tests/tests/light-push/index.node.spec.ts
- packages/tests/tests/light-push/single_node/index.node.spec.ts
- packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts
- packages/tests/tests/sharding/auto_sharding.spec.ts
- packages/tests/tests/sharding/static_sharding.spec.ts
- packages/tests/tests/store/index.node.spec.ts
- packages/tests/tests/store/multiple_pubsub.spec.ts
…patibili…"
This reverts commit 26ab836900d907b0ca185e6ad5fb6b3b548350fb.
- Resolves
- Related to
---
> chore: revert upgrade nwaku to 0.34.0

- .github/actions/npm/action.yml
- ci/publish.js
`npm i` custom action fails to run on release branch
Remove white spaces that bust the action functionality
- Resolves https://github.com/waku-org/js-waku/issues/2296
> chore: update ci npm command

- .github/workflows/ci.yml
- .github/workflows/playwright.yml
- package-lock.json
- packages/sdk/package.json
In the following commit `noise` package did introduce breaking changes but didn't bump major version leading to accidental update on our end due to `^` rule.
Remove `^`.
https://github.com/ChainSafe/js-libp2p-noise/commit/58c9fb997056060670ab98ddb3726469f6f833d6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
Relevant PRs:
https://github.com/waku-org/js-waku/pull/2317
https://github.com/waku-org/js-waku/pull/2315
---
> fix: downgraid chainsafe

- packages/tests/README.md
`interop` readme is a bit out of date
update it
Resolves: https://github.com/waku-org/js-waku/issues/2368
> chore: up interop readme

- package-lock.json
`npm audit` returns vulnerable packages
Update package-lock.json with result of `npm audit fix`, without `--force` flag, which replaces some of the vulnerable packages without breaking changes
- Resolves
- Related to
---
> fix: npm audit without force

- packages/core/src/lib/filter/filter.ts
Since old Filter is removed - we need to remove old code related to it.
Remove
- Resolves https://github.com/waku-org/js-waku/issues/2432
- Related to https://github.com/waku-org/js-waku/pull/2433
> chore: remove filter codec initiator

- karma.conf.cjs
- packages/sds/karma.conf.cjs
- packages/sds/package.json
No browser tests for sds package.
Enable Karma for sds package
---
> test: add browser tests for sds

- packages/core/src/lib/filter/filter.ts
- packages/core/src/lib/light_push/constants.ts
- packages/core/src/lib/light_push/index.ts
- packages/core/src/lib/light_push/light_push.ts
- packages/core/src/lib/light_push/protocol_handler.ts
- packages/core/src/lib/metadata/metadata.ts
- packages/core/src/lib/store/store.ts
- packages/core/src/lib/stream_manager/stream_manager.ts
- packages/interfaces/src/filter.ts
- packages/interfaces/src/light_push.ts
- packages/interfaces/src/metadata.ts
- packages/interfaces/src/protocols.ts
- packages/interfaces/src/sender.ts
- packages/interfaces/src/store.ts
- packages/sdk/src/filter/filter.ts
- packages/sdk/src/filter/subscription.ts
- packages/sdk/src/light_push/light_push.ts
- packages/sdk/src/light_push/utils.ts
- packages/sdk/src/peer_manager/peer_manager.ts
- packages/sdk/src/store/store.ts
- packages/sdk/src/waku/wait_for_remote_peer.ts
- packages/sdk/src/waku/waku.ts
- packages/tests/tests/light-push/index.node.spec.ts
- packages/tests/tests/light-push/multiple_pubsub.node.spec.ts
- packages/tests/tests/light-push/v2_interop.spec.ts
This PR improves LigthPush integration and covers other things.
Adds E2E test, removed redundancy etc.
---
> feat: improve lp3

- packages/core/src/lib/connection_manager/connection_limiter.ts
Seems TTL update for connected peers in peer store is not actually working as intended.
This was introduced in https://github.com/waku-org/js-waku/pull/2641
And it leads to Peer Store having peers without addresses being assigned to them.
Reason is: addresses have separate TTL and get discarded regardless of peer entity being present.
Fixing this in a way to persist addresses, potentially, can lead to more bugs as we might keep broken `maddr` there.
Remove TTL update logic and keep only re-bootstrapping. 
- Related to https://github.com/waku-org/js-waku/issues/2637
> chore: stop updating TTL for peer store
