waku-org/js-waku

src/lib/waku.spec.ts, src/lib/waku.ts, src/lib/waku_relay.spec.ts, src/test_utils/constants.ts
When playing around with tests frameworks, it was noticed that noise
was using entropy that lead to handles remaining open at the end of the
test run.
=> Reduce entropy usage in tests

.github/workflows/add-action-project.yml
"Read and write org and team membership, read and write org projects"
according to https://github.com/alex-page/github-project-automation-plus
=> Use custom token to have the correct rights

README.md
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix
- **What is the current behavior?** (You can also link to an open issue here)
Goes to dead URL
- **What is the new behavior (if this is a feature change)?**
Goes to https://forum.vac.dev/t/waku-web-app-using-js-waku/78
- **Other information**:
URL provided by D4nte
=> Fix dead URL on README

web-chat/src/App.tsx
With `websockify` instance running on jdev and pointing to fleet node.
=> Connect to the test fleet

web-chat/src/App.tsx, web-chat/src/ChatList.tsx, web-chat/src/Room.tsx
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature
- **What is the current behavior?** (You can also link to an open issue here)
Resolves #86 
Name and timestamp are printed for each message
Large amounts of space are used for each message
- **What is the new behavior (if this is a feature change)?**
Name and timestamp are only printed for first message from sender until someone else sends a message
Padding and margin around text eliminated to maximize screen real estate usage
=> Group sequential messages from same sender into single group, reduce CSS padding, and don't repeat sender name and timestamp

web-chat/src/App.tsx
If no new messages are received, the rendering does not change
as dupe messages are filtered out.
=> Always trigger store query at connection

package-lock.json, package.json, src/lib/waku_relay/index.ts
As it clutters the documentation and at this stage we do not expect
users to use inherited methods.
=> Do not inherit doc for Waku Relay

CHANGELOG.md, examples/cli-chat/src/chat.ts
Due to #201, Websocket protocol is not added by default if the caller
specifies a protocol for libp2p.
In the case cli-chat. We were using both tcp and ws.
As the web-chat already demonstrates usage of websocket protocol, we
cli-chat to tcp only.
=> Use tcp protocol only for cli-chat

CHANGELOG.md, package-lock.json, package.json
- **Breaking**: Websocket protocol is not automatically added anymore if the user specifies a protocol in `libp2p.modules`
when using `Waku.create`.
- **Breaking**: Options passed to `Waku.create` used to be passed to `Libp2p.create`;
Now, only the `libp2p` property is passed to `Libp2p.create`, allowing for a cleaner interface.
- Examples (cli chat): Use tcp protocol instead of websocket.  
- Enable access to `WakuMessage.timestamp`.
- Examples (web chat): Use `WakuMessage.timestamp` as unique key for list items.
- Doc: Link to new [topic guidelines](https://rfc.vac.dev/spec/23/) in README.
- Doc: Link to [Waku v2 Toy Chat specs](https://rfc.vac.dev/spec/22/) in README.
- Examples (web chat): Persist nick.
- Support for custom PubSub Topics to `Waku`, `WakuRelay`, `WakuStore` and …
=> Release 0.6.0

CHANGELOG.md, examples/cli-chat/src/chat.ts, src/lib/select_peer.ts, src/lib/waku_light_push/index.spec.ts, src/lib/waku_light_push/index.ts, src/lib/waku_relay/index.spec.ts, src/lib/waku_relay/index.ts, src/lib/waku_store/index.spec.ts, src/lib/waku_store/index.ts
By adding observer when mounting a React component, we end up with several observers being triggered when a message is received.
To remediate to this, we need to provide a clean up function that removes observers when unmounting a component, this clean up function can now use `deleteObserver`.
The lib consumer usually does not care what peer is use for store and light push protocol, as long as a peer is available. When querying a store or pushing a message via light push, we now select a random peer to use.
- Resolves #184
- Helps with #72
=> Use Set to facilitate removal of observers

examples/eth-dm/src/App.tsx, examples/eth-dm/src/BroadcastPublicKey.tsx, examples/eth-dm/src/messaging/SendMessage.tsx, examples/eth-dm/src/utils.ts, examples/eth-dm/src/waku.ts
There was an issue where the observers are added/removed continuously.
This is due to using `useEffect` on props.
By removing this component and passing the right dependencies to `useEffect` then it only gets called (and add/remove component) when `waku` changes (at initialisation).
Also implement few code clean up and improve resilience.
=> Fix Observer infinite loop

CHANGELOG.md, examples/eth-dm/src/messaging/SendMessage.tsx, examples/eth-dm/src/messaging/wire.ts, examples/eth-dm/src/waku.ts, src/lib/waku_message/version_1.ts
=> Use protobuf instead of JSON for direct messages

CHANGELOG.md, package-lock.json, package.json
- `WakuRelay.deleteObserver` to allow removal of observers, useful when
a React component add observers when mounting and needs to delete it
when unmounting.
- Keep alive feature that pings host regularly, reducing the chance of
connections being dropped due to idle.
Can be disabled or default frequency (10s) can be changed when calling
`Waku.create`.
- New `lib/utils` module for easy, dependency-less hex/bytes
conversions.
- New `peers` and `randomPeer` methods on `WakuStore` and
`WakuLightPush` to have a better idea of available peers;
Note that it does not check whether Waku node is currently connected
to said peers.
- Enable passing decryption private keys to `WakuStore.queryHistory`.
- Test: Introduce testing in browser environment (Chrome) using Karma.
- Add support for Waku Message …
=> Release 0.8.0

CHANGELOG.md, package-lock.json, package.json
- Examples (web-chat): New `/fleet` command to switch connection between
Status prod and test fleets.
- Export `generatePrivateKey` and `getPublicKey` directly from the root.
- Usage of the encryption and signature APIs to the readme.
- **Breaking**: Renamed `WakuRelay.(add|delete)PrivateDecryptionKey` to
`WakuRelay.(add|delete)DecryptionKey` to make it clearer that it
accepts both symmetric keys and asymmetric private keys.
- Align `WakuMessage` readme example with actual code behaviour.
=> Release 0.8.1

CHANGELOG.md, package-lock.json, package.json
- **Breaking**: Store Response Protobuf changed to align with nim-waku v0.5
([nim-waku#676](https://github.com/status-im/nim-waku/pull/676)).
=> Release 0.9.0

.cspell.json, CHANGELOG.md, src/lib/waku.ts, src/lib/waku_relay/constants.ts
Introduced new `relayKeepAlive` option on `Waku` with a default to 59s to send ping messages over relay to ensure the relay stream stays open.
This is a workaround until [js-libp2p#744](https://github.com/libp2p/js-libp2p/issues/744) is done as there are issues when TCP(?) timeouts and the stream gets closed
([#185](https://github.com/status-im/js-waku/issues/185), [js-libp2p#939](https://github.com/libp2p/js-libp2p/issues/939))
=> New relay keep alive feature

examples/web-chat/src/App.tsx, examples/web-chat/src/ChatList.tsx, examples/web-chat/src/Room.tsx
Only retrieve historical messages when starting the app.
This allows avoid re-rendering issues. This is an example dApp. No need
to waste time on React optimisation.
Resolves #246
=> Limit store retrievals

CHANGELOG.md, package-lock.json, package.json
- Relay and ReactJS guides and examples
([#56](https://github.com/status-im/js-waku/issues/56)).
- **Breaking**: The `WakuMessage` APIs have been changed to move
`contentTopic` out of the optional parameters.
- Examples (web-chat): Remove broken `/fleet` command.
- **Breaking**: Removed `DefaultContentTopic` as developers must choose
a content topic for their app; recommendations for content topic can
be found at https://rfc.vac.dev/spec/23/.
- `WakuMessage.payloadAsUtf8` returning garbage on utf-8 non-ascii
characters.
- `ChatMessage.payloadAsUtf8` returning garbage on utf-8 non-ascii
characters.
=> Release 0.10.0

CHANGELOG.md, src/lib/waku_store/history_rpc.ts, src/lib/waku_store/index.spec.ts, src/lib/waku_store/index.ts
Helps with #187 
Note: both `startTime` and `endTime` must be provided until https://github.com/status-im/nim-waku/issues/706 is resolved.
=> Added support for `startTime` and `endTime` in Store queries

CHANGELOG.md, package-lock.json, package.json
- Examples: New Ethereum Private Message Using Wallet Encryption
[Web App](./examples/eth-pm-wallet-encryption/README.md)
example that demonstrates the usage of `eth_encrypt` API (available on
Metamask) and EIP-712 for typed structured data signing.
- New `bootstrap` option for `Waku.create` to easily connect to Waku
nodes upon start up.
- Support for `startTime` and `endTime` in Store queries to filter by
time window as per [21/WAKU2-FTSTORE](https://rfc.vac.dev/spec/21/).
- Renamed `discover.getStatusFleetNodes` to
`discovery.getBootstrapNodes`;
Changed the API to allow retrieval of bootstrap nodes from other
sources.
- Examples: Renamed `eth-dm` to `eth-pm`; "Direct Message" can lead to
confusion with "Direct Connection" that
refers to low latency network connections.
- Examples …
=> Release 0.11.0

CHANGELOG.md, package-lock.json, package.json
- Examples (eth-pm): Encrypt Public Key Messages using symmetric encryption. 
- Guides: Encrypt messages using Waku Message Version 1.
- Allow passing decryption keys in hex string format.
- Allow passing decryption keys to `WakuStore` instance to avoid having to pass them at every `queryHistory` call.
- Allow passing decryption keys to `Waku` instance to avoid having to pass them to both `WakuRelay` and `WakuStore`.
- `Waku.waitForConnectedPeer` helper to ensure that we are connected to Waku peers when using the bootstrap option.
- **Breaking**: Moved `startTime` and `endTime` for history queries to a `timeFilter` property as both or neither must be passed; passing only one parameter is not supported.
- Renamed and promote the usage of `generateSymmetricKey()` to generate random …
=> Release 0.12.0

CHANGELOG.md, package-lock.json, package.json
- Upgrade libp2p libraries: @chainsafe/libp2p-noise@4.1.1, libp2p@0.32.4, libp2p-gossipsub@0.11.1.
- Connects to a limited number of bootstrap nodes, defaults to 1.
=> Release 0.13.0

CHANGELOG.md, package-lock.json, package.json
- `Error: Bootstrap requires a list of peer addresses` error when using `bootstrap: true` in `Waku.create`.
=> Release 0.13.1

CHANGELOG.md, examples/min-react-js-chat/package-lock.json, examples/min-react-js-chat/package.json, examples/store-reactjs-chat/package-lock.json, examples/store-reactjs-chat/package.json, package.json
=> Generate es6/es2015 code for ESM package

CHANGELOG.md, package-lock.json, package.json
- Examples: JS examples uses local ESM folder to replicate behaviour of
js-waku publish package.
- `TypeError` issue related to constructors using js-waku in a JS
project
([#323](https://github.com/status-im/js-waku/issues/323)).
=> Release 0.14.2

.github/workflows/ci.yml
It was not used as bufbuild always gets installed.
Installation only takes a few seconds so the caching is not needed.
=> ci: Remove bufbuild caching

.cspell.json, package-lock.json, package.json, src/lib/enr/constants.ts, src/lib/enr/create.ts, src/lib/enr/enr.spec.ts, src/lib/enr/enr.ts, src/lib/enr/index.ts, src/lib/enr/keypair/constants.ts, src/lib/enr/keypair/index.spec.ts, src/lib/enr/keypair/index.ts, src/lib/enr/keypair/secp256k1.ts, src/lib/enr/keypair/types.ts, src/lib/enr/types.ts, src/lib/enr/v4.ts, tsconfig.json
Work towards #75
Imported from D4nte/discv5#1
Replaced bcrypto backend with secp256k1.
Also imported all original tests to ensure behaviour is the same.
Main difference between bcrypto and secp256k1 is that bcrypto seems to drop the recovery id from signatures. Meaning signatures encoded in ENRs are 64 bytes.
This is fair because the public key is usually present in the ENR field `secp256k1` and hence does not need to be recovered from the signature.
Done as a separate PR as there are several points to tackle to #305 to work on latest main such as using a more browser friendly lib for DNS-over-HTTPS than `dohdec`.
=> Add ENR Support with `multiaddrs`

examples/web-chat/package.json
By not transpiling for older browsers that do not support BigInt.
Example solution for #358.
=> Fix Cannot convert BigInt value to a number

.github/workflows/ci.yml
This is a browser library, there is little to no value to run the CI
on several OSes.
=> Remove run on macos

CHANGELOG.md, src/lib/waku.ts, src/lib/waku_message/index.spec.ts, src/lib/waku_message/index.ts, src/lib/waku_relay/index.node.spec.ts, src/lib/waku_relay/index.ts, src/lib/waku_store/index.node.spec.ts, src/lib/waku_store/index.ts
When using `addDecryptionKey`. This enables the user to limit the number
of useless decryption attempts done and improve performance.
Resolves #408.
=> Allow specifying decryption methods and content topic

CHANGELOG.md, package-lock.json, package.json
- Implement DNS Discovery as per [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459),
with ENR records as defined in [31/WAKU2-ENR](https://rfc.vac.dev/spec/31/);
Available by passing `{ bootstrap: { enrUrl: enrtree://... } }` to `Waku.create`.
- When using `addDecryptionKey`,
it is now possible to specify the decryption method and the content topics of the messages to decrypt;
this is to reduce the number of decryption attempt done and improve performance.
- Test: Upgrade nim-waku node to v0.6.
- **Breaking**: Renamed `getBootstrapNodes` to `getNodesFromHostedJson`.
- Minimum node version changed to 16.
- **Breaking**: Changed `Waku.create` bootstrap option from `{ bootstrap: boolean }` to `{ bootstrap: BootstrapOptions }`.
Replace `{ boostrap: true }` with `{ boostrap: { default: true } …
=> Release 0.15.0

package-lock.json, package.json, src/lib/discovery/bootstrap.ts, src/lib/waku.node.spec.ts, src/lib/waku_light_push/index.node.spec.ts, src/lib/waku_message/index.node.spec.ts, src/lib/waku_relay/index.node.spec.ts, src/lib/waku_store/index.node.spec.ts, src/test_utils/nim_waku.node.spec.ts, src/test_utils/nim_waku.ts
Also remove tests where nim-waku connects to js-waku as this is not a plausible scenario in the browser (yet).
=> Use websocket instead of tcp in interop tests

CHANGELOG.md, package-lock.json, package.json
- Test: Upgrade nim-waku node to v0.7. 
- Doc: Renamed "DappConnect" to "Waku Connect".
- Docs: API Docs are now available at https://js-waku.wakuconnect.dev/.
- **Breaking**: Replace `waitForConnectedPeer` with `waitForRemotePeer`; the new method checks that the peer is ready before resolving the promise.
=> Release 0.16.0

.github/dependabot.yml
Update the npm manifest file to relax the version requirements as
js-waku is a library.
=> Use widen strategy

CHANGELOG.md, package-lock.json, package.json, src/lib/discovery/dns_over_https.ts, src/lib/discovery/enrtree.ts, src/lib/enr/enr.spec.ts, src/lib/enr/enr.ts, src/lib/enr/keypair/index.ts, src/lib/enr/keypair/secp256k1.ts, src/lib/enr/v4.ts, src/lib/utils.ts, src/lib/waku.ts, src/lib/waku_message/index.node.spec.ts, src/lib/waku_message/index.ts, src/lib/waku_relay/index.ts, src/test_utils/constants.ts
The latter does not use Buffer dependency.
Also, consumers are likely to use `ethers` for web3 purposes meaning space is save as part of the library is already present as a dep.
=> Replace rlp with ethers' rlp

CHANGELOG.md, package-lock.json, package.json
- Replaced `rlp` dependency with `@ethersproject/rlp`.
- **Breaking**: `staticNoiseKey` changed from `Buffer` to `Uint8Array`.
- Implement Waku Store 2.0.0-beta4. The `WakuMessage.timestamp` field now stores nanoseconds over the wire.
- **Breaking**: `HistoryRPC.createQuery` takes `Date` instead of `number` for `startTime` and `endTime`.
- `base64url` and `bigint-buffer` dependencies.
=> Release 0.18.0

CHANGELOG.md, examples/web-chat/src/Message.ts, src/lib/discovery/dns.ts, src/lib/discovery/dns_over_https.ts, src/lib/enr/enr.ts, src/lib/waku_message/index.ts
`bytesToUtf8` replaced a previously used library. The previous library did not throw when failing to decode whereas `bytesToUtf8` does. Need to handle those errors.
=> Handle errors thrown when converting to utf-8

CHANGELOG.md, package.json
While this library targets the browser, it is sometimes helpful to use
it in need for experiments.
For example: https://github.com/status-im/js-waku/pull/588
=> Add exports field for node

CHANGELOG.md, src/lib/waku_message/index.ts, src/lib/waku_store/history_rpc.ts
It was using microseconds.
Fixes #597
=> `WakuMessage.timestamp` field must use nanoseconds

CHANGELOG.md, package-lock.json, package.json
- New `pubsub_topic` field on the `cursor` of Waku Store queries ([#585](https://github.com/status-im/js-waku/issues/595)).
- Add `exports` to `package.json` for NodeJS usage (not officially supported but helpful for experiments).
- Handle errors thrown by `bytesToUtf8`.
- `WakuMessage.timestamp` field must use nanoseconds (was using microseconds).
- Removed `ecies-geth` dependency.
=> Release 0.19.0

CHANGELOG.md, examples/web-chat/src/App.tsx, src/lib/discovery/bootstrap.ts, src/lib/waku.node.spec.ts
It was awkward to use our own APIs together, even more so to write documentation about them. Now fixed.
=> Allow passing multiaddr to `bootstrap.peers`

CHANGELOG.md, package-lock.json, package.json
- Examples: Add Relay JavaScript example.
- **Breaking**: Moved utf-8 conversion functions to `utils`.
- Froze `libp2p-gossipsub` to `0.13.0` as new patch version bring breaking changes.
=> Release 0.20.0

examples/relay-reactjs-chat/package-lock.json, examples/relay-reactjs-chat/package.json, examples/relay-reactjs-chat/src/App.js
`protons@3.0.1` now generates TypeScript code and needs to be used with `tsc`.
Doc updated with https://github.com/vacp2p/docs.wakuconnect.dev/pull/50
=> Replaces protons with protobufjs

CHANGELOG.md, package-lock.json, package.json
- Replaced `secp256k1` and hence `elliptic` dependencies with `@noble/secp256k1`,
reducing package size, number of dependency and removing need for `crypto-browserify` polyfill.
=> Release 0.22.0

.cspell.json, CHANGELOG.md, package-lock.json, package.json, src/lib/discovery/fetch_nodes.spec.ts, src/lib/enr/enr.node.spec.ts, src/lib/enr/enr.spec.ts, src/lib/enr/enr.ts, src/lib/enr/keypair/index.ts
Removing deprecation warning at installation.
=> Replace deprecated `multihashes` with `multiformats`

package-lock.json, package.json
- Some dependencies that were used but not declared (often transient).
- Replaced deprecated `multihashes` with `multiformats`.
- No more `assert` usage.
=> Release 0.23.0

examples/relay-reactjs-chat/src/App.js
When running the app on a development server, the React list of mapped messages produces a warning that the children in a list should have a unique key prop:
Add a unique key to the list element in the App.js component.
Any unique key will do here, but the timestamp seems to work unless the maintainers refactor for a better id. 
A timestamp may not be ideal if multiple messages with the same timestamp come in. Perhaps a uuid would
work, but perhaps that is too heavy handed for an example, although this may be a choice for a production
implementation.
=> update unique key to React list element in relay-reactjs-chat app

src/lib/waku_store/index.ts
Expected proto3 behaviour, just no message returned.
=> fix: do not throw on lack of response

package.json
Needed to access `PeerDiscoveryStaticPeers`.
=> fix: add peer_discovery_static_list to exports map

package.json
Importing anything from TypeScript in `js-waku/lib/` (`v0.25.0-rc.0`) does not work. It can't find the types despite the `exports.*.types` in `package.json`.
This solution was inspired by `libp2p` ([example in `@libp2p/interfaces`](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interfaces/package.json#L24-L39)), and just adds `typesVersions` to `package.json`.
Documentation: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#folder-redirects-using-
- See https://github.com/status-im/js-waku/issues/891#issuecomment-1217388556
=> fix: type export via `typesVersions`

src/lib/waku_light_push/index.node.spec.ts, src/lib/waku_store/index.node.spec.ts, src/test_utils/nwaku.node.spec.ts, src/test_utils/nwaku.ts
Fix a number of issues with current handling of `nwaku` in tests, also makes it easier to use a different nwaku node than the one in the submodule.
=> Parameterize test framework

src/lib/waku_message/index.ts
While they do not need to be decoded, they might still be used.
e.g. timestamp, network connectivity, etc.
=> fix: do not discard messages with no payload

src/index.ts
It is already present in the exports map.
=> fix: do not export waitForRemotePeer from index

.size-limit.cjs, package.json, rollup.config.js
This module will just consume a generate Waku and Waku Relay interfaces so we already we want to extract it.
It is also one opinionated to handle connection management, other ways might come with #914.
=> include wait_for_remote_peer in exports map

CHANGELOG.md, package-lock.json, package.json
None-exhaustive list of changes:
- Published files moved from `build` to `dist/`.
- Migrate from ts-proto to protons;
the latter does not bring Buffer/Long deps, is ESM compatible and remove the need for bufbuild and protoc.
- Move package to `"type": "module"`, it is now a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
- Use ESM code in Mocha and Karma tests.
- Upgrade `dns-query` dependency, breaking change on `DnsNodeDiscovery` API.
- Bump many libp2p libraries to their latest version (which usually are pure ESM).
- Replace webpack with parcel for bundling
- Examples: Updated store-js and relay-js to demonstrate usage of ESM bundle in `<script>` tag.
- Remove need to polyfill `buffer`.
- **breaking**: Various API changes. Refer to tests to …
=> Release 0.25.0

CHANGELOG.md, package.json
This reverts commit cf6eafdff356e8339e8589fb2b3c01b5da241879.
The polyfill is actually needed because `util.inspect.custom` is called.
=> Revert "fix: util polyfill not needed"

CHANGELOG.md, package-lock.json, package.json, src/lib/waku.ts
- `createLightNode` to create a Waku node for resource restricted environment with Light Push, Filter and Relay.
- `createPrivacyNode` to create a Waku node for privacy preserving usage with Relay only.
- `createFullNode` to create a Waku node for with all protocols, for **testing purposes only**.
- `Waku` is now defined as an interface with `WakuNode` an implementation of it.
- `createWaku` is deprecated in favour of `createLightNode` and `createPrivacyNode`.
- `waitForRemotePeer` can throw, default behaviour has changed.
- `addPeerToAddressBook` is now async.
- API Docs moved to https://js.waku.org/
- test: fix typing for nwaku JSON RPC responses.
=> Release 0.27.0

CHANGELOG.md, src/lib/select_peer.ts, src/lib/waku_filter/index.ts, src/lib/waku_light_push/index.ts, src/lib/waku_store/index.node.spec.ts, src/lib/waku_store/index.ts
This enables the consumer to decide between:
1. Waiting for all promises, less efficient but maintain order;
2. Process promises as they resolve, faster to get messages through but
disrupt message order.
Helps with #937
Resolves #750
=> feat: store callback takes promises 

CHANGELOG.md, package-lock.json, package.json
- Correct options type for `createFullNode` & `createPrivacy` to enable passing gossipsub options.
- `WakuStore` now provides several APIs: `queryGenerator`, `queryCallbackOnPromise`, `queryOrderedCallback`;
each provides different guarantees and performance.
=> Release 0.28.0

CHANGELOG.md, package-lock.json, package.json
- `WakuRelay.addObserver` now returns a function to delete the observer.
- `queryCallbackOnPromise`'s return value has been simplified to `Promise<void>`.
- doc: clarified behaviour of `WakuStore` query functions.
=> chore: release 0.28.1

CHANGELOG.md, package-lock.json, package.json
- Waku message encoding and decoding is more generic, to enable upcoming feature such as [RLN](https://rfc.vac.dev/spec/17/) & [Noise](https://rfc.vac.dev/spec/43/);
it also enables separating the `version_1` module out to reduce bundle size and improve cross-platform compatibility when not used.
- Due to the change above, all APIs that handle messages have changed to receive a `Decoder` or `Encoder`.
=> Release 0.29.0

CHANGELOG.md, src/lib/waku_store/index.node.spec.ts, src/lib/waku_store/index.ts
=> fix: `queryOrderedCallback` not stopping when callback returns true

CHANGELOG.md, package-lock.json, package.json
- `RateLimitProof` field in Waku Message protobuf for RLN.
- `Message` interface changed to ensure implementations do not omit fields.
- `Decoder` and `Encoder` interfaces change to better express what the function members do.
- Incorrect cursor encoding in Store queries.
- `WakuStore.queryOrderedCallback` not stopping when callback returns true.
- Support for Waku Store 2.0.0-beta3.
=> Release 0.30.0

.github/workflows/conventional-commits.yml
By splitting the repo in multiple packages, it is going to be more difficult to manually maintain a changelog. Using conventional commit, we can automatically generate the changelog from PR titles.
=> chore: add conventional commit check for PRs

packages/core/src/lib/waku_filter/index.ts, packages/core/src/lib/waku_message/version_0.ts, packages/core/src/lib/waku_relay/index.ts, packages/core/src/lib/waku_store/index.ts, packages/interfaces/src/index.ts, packages/message-encryption/src/index.ts, packages/tests/package.json, packages/tests/tests/filter.node.spec.ts, packages/tests/tests/relay.node.spec.ts, packages/tests/tests/waku.node.spec.ts
While the data structure are similar, they serve different purposes. Having the same type has show to confuse API consumers
Resolves #979
=> feat!: split outgoing and incoming message interface

package-lock.json, packages/core/package.json, packages/create/package.json
Some `create` dependencies were still in the `core` package.json file.
=> fix(core,create): dependencies mismatch

packages/core/CHANGELOG.md, packages/core/src/lib/to_proto_message.spec.ts, packages/core/src/lib/to_proto_message.ts, packages/core/src/lib/waku_message/topic_only_message.ts, packages/core/src/lib/waku_message/version_0.spec.ts, packages/core/src/lib/waku_message/version_0.ts, packages/core/src/proto/filter.ts, packages/core/src/proto/light_push.ts, packages/core/src/proto/message.proto, packages/core/src/proto/message.ts, packages/core/src/proto/store.ts, packages/interfaces/src/index.ts, packages/message-encryption/src/index.ts, packages/tests/tests/store.node.spec.ts
Support for `ephemeral` (https://github.com/vacp2p/rfc/pull/532, https://github.com/waku-org/go-waku/pull/305) on `MESSAGE` lacks in `js-waku`.
Since `nwaku` already implements this, we now introduce passing `ephemeral` as a boolean on the API level within js-waku. 
If no value is provided, the default of `false` is set.
Also added tests to check for correct behavior.
`true` -> don't store the message
`false` -> store the message
Read the RFC on more info: https://rfc.vac.dev/spec/14/
=> feat!: add ephemeral support

packages/tests/tests/ephemeral.node.spec.ts, packages/tests/tests/filter.node.spec.ts, packages/tests/tests/light_push.node.spec.ts, packages/tests/tests/store.node.spec.ts
As full node was only necessary due to an issue nwaku v0.11.
Ref: https://github.com/status-im/nwaku/pull/1090
=> test: use `createLightNode` instead of a full node

package-lock.json, packages/core/CHANGELOG.md, packages/core/package.json
This dep often has breakings changes on type and is used by several APIs. Declaring as an optional peer dependency will hopefully help the user know what version to install.
=> feat: add `@multiformats/multiaddr` as peer dep

.github/workflows/ci.yml, packages/core/src/lib/waku_store/index.ts, packages/interfaces/src/index.ts
Addresses a few (non-blocking/breaking) comments/changes requested on the initial PR introducing cursor support for the store protocol.
- improves doc for the cursor usage
- increases code readability for the usage of `cursor` in `paginate()`
- better/remove redundant usage of types
- A followup to https://github.com/waku-org/js-waku/pull/1024
=> feat: improve the cursor API

packages/interfaces/src/index.ts, packages/peer-exchange/src/rpc.ts, packages/peer-exchange/src/waku_peer_exchange.ts, packages/tests/tests/peer_exchange.node.spec.ts
Issue: https://github.com/waku-org/nwaku/issues/1408#issuecomment-1326708100
As a follow-up to the above-mentioned issue, it was realized that the current nwaku peer-exchange implementation requires setting up a callback response handler which was implemented in the scope of this PR as a solution.
- ~~Still blocked by the parent issue. Reference: https://github.com/waku-org/nwaku/issues/1408#issuecomment-1327325084~~
=> peer-exchange: bind a response handler

packages/core/src/lib/waku_peer_exchange/index.ts, packages/interfaces/src/index.ts
The `PeerExchangeRPC` query returns us a List<ENR> which is of type List<`Uint8Array`> which should be converted to the interface implemented `ENR` for consistency
Using the already implemented `ENR` class to convert the `Uint8Array` to `ENR`
- ~~Blocked by the parent PR: https://github.com/waku-org/js-waku/pull/1027~~
=> refactor: use the ENR type for PeerExchangeResponse

.eslintrc.json
We use `debug` across the codebase, this ensures no `console.log` slips in by mistake.
=> chore: make no-console an error

package.json
Fixes errors like:
```
SyntaxError: Cannot use import statement outside a module
```
https://ci.infra.status.im/job/website/job/js.waku.org/4/
=> package.json: set type to module

.github/workflows/ci.yml, packages/tests/src/nwaku.ts
Node recently moved its LTS to 18, from 16 and we should run our CI on 18 as well.
Part of change was using `127.0.0.1` instead of `localhost` while making the request:
There is a change in how Node does DNS resolution in Node 18 vs 16 -- `localhost` resolves to `::1`, which is the equivalent of `127.0.0.1` but in IPv6 instead of IPv4. The server however is only listening on IPv4.
Reference:
https://github.com/nodejs/node/issues/40702#issuecomment-958143154
- Resolves https://github.com/waku-org/js-waku/issues/1023
=> chore: upgrade to node 18

packages/message-encryption/CHANGELOG.md, packages/message-encryption/src/ecies.ts, packages/message-encryption/src/symmetric.ts
Enables API consumer to use the types.
Ref https://github.com/waku-org/js-waku-examples/pull/168#discussion_r1052761319
=> fix: export `Encoder` and `Decoder` types

packages/core/src/lib/wait_for_remote_peer.ts
This is because peer exchange is still experimental and not enabled on all prod fleets.
The issue is that we could be connected to a remote peer with relay/ filter/lightpush yet never resolve because peer exchange is missing.
This also shows the limit of this function logic which should be addressed as we dive deeper in peer management.
=> feat!: remove peer exchange from protocols to wait on by default

packages/core/src/lib/waku.ts
ref: https://github.com/waku-org/js-waku/issues/949
sets `ephemeral: true` for relay ping messages
=> fix: add `ephemeral: true` to relay pings

.github/workflows/ci.yml
Currently fails due to various issues. Can be re-enabled once sorted.
=> chore: disable go-waku and nwaku master CIs jobs

.github/workflows/ci.yml
All issues have been resolved on nwaku master.
Note that 0.14.0 contains regressions and hence cannot be used for CI run.
=> chore: re-enable nwaku master CIs jobs

package-lock.json, packages/proto/package.json, packages/proto/src/lib/filter.ts, packages/proto/src/lib/light_push.ts, packages/proto/src/lib/message.ts, packages/proto/src/lib/peer_exchange.ts, packages/proto/src/lib/store.ts, packages/proto/src/lib/topic_only_message.ts
Notable change: optionality of singular fields and optional values.
See https://github.com/ipfs/protons/releases
Fixes #921
=> chore!: bump protons from 5.1.0 to 7.0.2

release-please-config.json
Follow up to `release-please` config to bump only `patch`.
Solution is to use valid property which is not well documented - https://github.com/googleapis/release-please/commit/8a7bfc165755cec97cc9a3baa39ccd21e719644c#diff-545bcd69c10300cbce0642d6970d8ccbff666d1e2b70b048084d4c6ec8b1e3d7
Example of release PR: https://github.com/waku-org/js-waku/pull/1175
Previous PR to https://github.com/waku-org/js-waku/pull/1155
=> chore: release bump patch only 

packages/core/CHANGELOG.md, packages/create/CHANGELOG.md, packages/dns-discovery/CHANGELOG.md, packages/enr/CHANGELOG.md, packages/interfaces/CHANGELOG.md, packages/message-encryption/CHANGELOG.md, packages/peer-exchange/CHANGELOG.md, packages/proto/CHANGELOG.md, packages/utils/CHANGELOG.md
Add missing CHANGELOG.md in some packages:
- peer-exchange
- proto
- utils
And update note in the existing CHANGELOG.md 
- Related to https://github.com/waku-org/js-waku/pull/1176
=> chore: update note in CHANGELOG and add missing

packages/dns-discovery/src/index.ts, packages/peer-exchange/src/waku_peer_exchange_discovery.ts
If we `continue` when the peer is already known by the `peerStore` then the next step of checking the tags is useless (no tags if peer is not known).
There are two ways around it:
1. either do nothing if peer is already in peer store
2. OR, do nothing if peer is in peer store and is already tagged
I opted for the second approach to ensure all peers are tagged properly.
=> fix(dns-discovery/peer-exchange): check if peer is already tagged

packages/core/src/lib/filter/index.ts, packages/core/src/lib/message/topic_only_message.ts, packages/core/src/lib/message/version_0.spec.ts, packages/core/src/lib/message/version_0.ts, packages/core/src/lib/relay/index.ts, packages/core/src/lib/store/index.ts, packages/interfaces/src/message.ts, packages/message-encryption/src/decoded_message.ts, packages/message-encryption/src/ecies.spec.ts, packages/message-encryption/src/ecies.ts, packages/message-encryption/src/symmetric.spec.ts, packages/message-encryption/src/symmetric.ts, packages/tests/tests/filter.node.spec.ts, packages/tests/tests/relay.node.spec.ts, packages/tests/tests/store.node.spec.ts
Needed for deterministic message hash.
Ref: #1208
=> feat!: expose pubsub topic in `IDecodedMessage`

.cspell.json, packages/core/.prettierignore, packages/create/.prettierignore, packages/dns-discovery/.prettierignore, packages/enr/.prettierignore, packages/interfaces/.prettierignore, packages/message-encryption/.prettierignore, packages/peer-exchange/.prettierignore, packages/proto/.prettierignore, packages/utils/.prettierignore
Because CHANGELOG is auto updated now it contradicts with prettier check.
Ignore it's checking by prettier and cspell.
=> fix: prettier and cspell ignore CHANGELOG

.github/dependabot.yml
Dependabot is working well now that config was fixed for monorepo so we can increase the number of ongoing PRs for deps.
=> chore: update dependabot reviewers and number of max PRs

packages/core/src/lib/keep_alive_manager.ts
Note that this keep alive mechanism should probably be removed.
=> fix: add payload to relay ping messages to avoid poor relay peer scoring

.github/workflows/ci.yml
Makes `latest` default tag for publishing of `js-waku` packages.
=> chore: make latest default tag for publishing

.github/workflows/ci.yml
Use NPM token in `.npmrc` instead of `NODE_AUTH` env variable.
=> chore: use npm token

.release-please-manifest.json, package-lock.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/create/package.json, packages/message-encryption/package.json, packages/peer-exchange/package.json, packages/tests/package.json
Because of a wrong publish of `@waku/core` I caused the next version should be skipped.
Manually bump it's value in the repo.
=> chore: bump core version

packages/core/CHANGELOG.md
`release-please` got confused by the manual core version bump and put all prev changes to the log.
Try to make changelog of the core package following proper format as it might prevent this confusion.
=> fix: update core changelog

packages/core/src/lib/message/version_0.spec.ts, packages/core/src/lib/message/version_0.ts, packages/message-encryption/src/ecies.spec.ts, packages/message-encryption/src/ecies.ts, packages/message-encryption/src/symmetric.spec.ts, packages/message-encryption/src/symmetric.ts
Waku Messages are considered invalid if the content topic is undefined or an empty string.
Avoid user error by throwing.
=> feat!: ensure content topic is defined

packages/core/src/lib/waku.ts
In new version of `@libp2p` they removed internal mapping from string to `Multiaddr` 
Create transform function on our side and update types.
=> feat: add mapping function to multiaddr of peerid

packages/core/src/lib/relay/index.ts
There is an assumption that `StrictNoSign` messages always have `msgId` generated by `sha256`.
To reduce potential problems explicitly define `msgIdFn` and pass to `GossipSub`.
- Resolves https://github.com/waku-org/js-waku/issues/1179
=> feat: use sha256 for Relay msgIdFn

package-lock.json, package.json, packages/core/src/lib/filter/index.ts, packages/core/src/lib/relay/index.ts, packages/interfaces/src/index.ts, packages/interfaces/src/misc.ts, packages/interfaces/src/receiver.ts, packages/tests/tests/utils.spec.ts, packages/utils/package.json, packages/utils/src/common/index.ts, packages/utils/src/common/to_async_iterator.ts
It is convenient to wait for messages and retrieve them in order.
Create transformer from `IReceiver` to `IAsyncIterator`.
Related: https://github.com/waku-org/js-waku-examples/pull/229
=> feat: toSubscriptionIterator impl for IReceiver

packages/interfaces/src/message.ts
Decoders are expected to expose this field in their return type. Somehow missed in previous PRs.
=> feat: expose `meta` on `IDecodedMessage`

packages/tests/tests/utils.spec.ts
`go-waku` tests started to hang after `utils.spec.ts` introduction.
Add timeout.
=> fix: add timeout to utils test

packages/tests/tests/utils.spec.ts, packages/utils/src/common/to_async_iterator.ts
Because iterator is using `while true` inside it is not getting terminated by `mocha` timeouts in local and sometime in pipeline environment.
It also is capable of blocking the main thread.
Add options to configure timeout.
Add idle state to the generator.
=> chore: add iterator timeout

release-please-config.json
Had to apply fix to force `release-please` to release `relay` package as `0.0.1`.
Remove enforcement. 
https://github.com/waku-org/js-waku/pull/1366
=> chore: remove forced relay version

.cspell.json, packages/core/src/lib/connection_manager.ts, packages/interfaces/src/connection_manager.ts
This PR addresses point 2 & point 3 of https://github.com/waku-org/js-waku/issues/1326
- multiple discovered peers are dialed in parallel until max limit is reached
- connection to a bootstrap peer is dropped if more than >set bootstrap connections are formed
- https://github.com/waku-org/js-waku/pull/1379 should be merged first
=> feat: dial multiple peers in parallel

release-please-config.json
In order to release `@waku/sdk` as `0.0.16` enforced version was used.
Remove forced version
- Related to #1353
=> chore: remove forced release version of sdk

.github/workflows/add-action-project.yml
Previous version uses API that will be deprecated.
=> chore: upgrade add-to-project GitHub action

.github/CODEOWNERS
@fryorcraken is the reviewer by default and folks should add others manually
use @waku-org/js-waku-developers as code owner
=> chore: add js-waku-developers as code owners

.github/workflows/ci.yml
It happens that our CI fails due to timeouts.
Add some amount of additional retry attempts, 3 for now.
=> chore: add retry to test steps of ci

.github/workflows/ci.yml
When nwaku creates a release it needs to run the jswaku tests (ideally automatically) against the release
Added workflow_call so the ci can be invoked via reusable workflows
Exclude based on the caller input the un-needed jobs
=> chore: added workflow_call to the ci.yml

.github/actions/npm/action.yml
For some reason `npm ci` is used on the release branch and it fails, which is expected.
Fall back on plain `npm i` for now before I understand what caused it.
=> fix: use npm i always (for now)

packages/tests/src/node/node.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/filter/unsubscribe.node.spec.ts, packages/tests/tests/relay.node.spec.ts
When interop testing with nwaku, tests did not subscribe nwaku to the default pubsub topic. Those tests only worked so far because of the default behavior of nwaku WAS to subscribe to the default pubsub topic and cache messages received on it.
With https://github.com/waku-org/nwaku/pull/1983 this is no longer the case.
Tests that call "get_waku_v2_relay_v1_messages" must call "post_waku_v2_relay_v1_subscriptions" before hand. Otherwise no messages will be cached.
=> fix: explicit nwaku subscriptions in tests

packages/core/src/lib/light_push/index.ts, packages/interfaces/src/protocols.ts, packages/tests/tests/light-push/index.spec.ts
`SendError.NO_RPC_RESPONSE` has been removed in favour of `SendError.REMOTE_PEER_FAULT` and `SendError.REMOTE_PEER_REJECTED`.
Resolves #1553
=> fix!: catch stream creation promise rejection for lightPush.send

packages/core/src/lib/stream_manager.ts, packages/tests/tests/waku.node.spec.ts
=> fix: catch top level exception when preemptively creating streams

packages/dns-discovery/src/constants.ts
Enrtrees were regenerated. Need to update the old one.
DNS discoverty should continue to work.
=> feat: update enrtree

packages/tests/tests/filter/multiple_pubsub.node.spec.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/light-push/multiple_pubsub.node.spec.ts
Saw a test failing on nwaku side because nwaku was missing ensureSubscriptions call
Added the call wherever it was missing
=> chore: add missing ensureSubscriptions call

packages/tests/.mocharc.json, packages/tests/README.md, packages/tests/src/run-tests.js
With parallel mode we cannot single out tests locally
Disabling parallel mode for local execution
=> chore: disable paralles runs locally

packages/core/src/lib/filter/index.ts
I got an exception about undefined res - seems 
```
waku:filter:v2 Error pinging:  +11ms TypeError: res[0] is undefined
```
Seems like this https://github.com/waku-org/js-waku/commit/d049ebbc3417e5c20eccba3aa1b9fc5382e8d7fc only fixed `subscribe` and `ping` and `unsubscribe` still needed the check
Add check and throw an error for empty response
=> fix: handle all empty responses in filter

.github/workflows/ci.yml, .github/workflows/pre-release.yml, CONTRIBUTING.md
`pre-release` on master on every push can create clutter in our npm repository in a long run
Make the job run by request
Ref: https://github.com/waku-org/js-waku/issues/1543
=> chore: make pre-release manual

package-lock.json, package.json
Running browser tests using Karma was not working locally on macOS https://github.com/waku-org/js-waku/issues/1707
The main culprit was the `karma-webpack` plugin. This PR modifies `package.json` to use the latest commit of the github repository instead of published npm package. The code in the repository has the fix, but the npm package has not been published since Feb 2021.
- Resolves #1707
=> chore: fix karma webpack

.cspell.json, packages/utils/.mocha.reporters.json, packages/utils/.mocharc.cjs, packages/utils/package.json, packages/utils/src/common/sharding.spec.ts, packages/utils/src/common/sharding.ts
There is currently no function for validating content topics used for autosharding
This PR adds a function to sharding utils which validates that a string is a valid content topic in the context of autosharding
- Related to #1710
=> feat: add function to validate autoshard content topic

package-lock.json, packages/utils/package.json, packages/utils/src/common/sharding.spec.ts, packages/utils/src/common/sharding.ts
In order to determine the pubsub topic to use for a content topic in the context of autosharding, we need to map the content topic to a shard number using the following algorithm: https://rfc.vac.dev/spec/51//#algorithm
Add a function to utils, which, given a string and number of shards, validates the content topic and returns which shard index to use.
Also adds a function that, given a content topic, will use the above function to determine the shard index and return the pubsub topic
- Resolves #1712
=> feat: add function for determining shard index from content topic

.github/dependabot.yml
js-waku developers are automatically added as reviewers.
=> chore: remove reviewers for dependabot.

.github/workflows/test-node.yml
An improvement that works fine for interop testing framework and I think it's good to have it here as well.
Jobs will have a summary with the link to the report:
=> chore: add test summary to github actions run

.github/workflows/test-node.yml
I saw that some logs are causing [failures](https://github.com/waku-org/js-waku/actions/runs/7269288370/job/19806681485#step:13:19) in the CI
Added a script that should sanitize the log names
=> chore: sanitize test log names before uploading

packages/tests/tests/light-push/index.node.spec.ts
The max message size reduction in `nim-waku` ( see [this](https://github.com/waku-org/nwaku/pull/2298) ) made the "Fails to push message with large meta" test fail because the `nwaku` didn't accept such a big message and therefore its response is different than the expected by the test.
In this PR, we are reducing the msg size sent in the "Fails to push message with large meta" test by the same amount of bytes that the max msg size is being reduced in `nim-waku`.
More details:
The "Fails to push message with large meta" test used 10 ** 6 when `nwaku` node had MaxWakuMessageSize == 1MiB ( `1*2^20` .)
`nwaku` establishes the max lightpush msg size as `const MaxRpcSize* = MaxWakuMessageSize + 64 * 1024`
see:
https://github.com/waku-org/nwaku/blob/07beea02095035f4f4c234ec2dec1f365e6955b8/waku/ …
=> test: light-push/index.node.spec.ts: adjust metadata size to nwaku max size adjustment

.vscode/settings.json, packages/core/src/index.ts, packages/core/src/lib/base_protocol.ts, packages/core/src/lib/connection_manager.ts, packages/core/src/lib/metadata/index.ts, packages/core/src/lib/wait_for_remote_peer.ts, packages/core/src/lib/waku.ts, packages/interfaces/src/metadata.ts, packages/interfaces/src/protocols.ts, packages/interfaces/src/waku.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/multiple_pubsub.node.spec.ts, packages/tests/tests/light-push/utils.ts, packages/tests/tests/store/multiple_pubsub.spec.ts, packages/tests/tests/store/utils.ts, packages/tests/tests/wait_for_remote_peer.node.spec.ts
Parent/origin: #https://github.com/waku-org/js-waku/pull/1756
There is a requirement to wait for ~50/100ms after a `peer:connect` event is fired as the Metadata Protocol is an async operation for which we need to wait to populate shard info, or we are disconnected if there is a cluster ID mismatch.
We need to wait for the Metadata protocol to complete before we can assume the peer is ready to be used to open connections reliably.
- Add check for successful metadata handshakes in `waitForRemotePeer`
- Also make fixes around enabling sharding for nwaku nodes (https://github.com/waku-org/nwaku/issues/2259)
Can still foresee a case where a peer that is connected is used for a protocol instantly, thus creating a race condition. 
Perhaps a more protocol-knit check should be added. Will also be …
=> feat: use metadata protocol for awaiting connection to remote peer

packages/core/src/lib/base_protocol.ts, packages/core/src/lib/filter/index.ts, packages/core/src/lib/light_push/index.ts, packages/core/src/lib/message/version_0.ts, packages/core/src/lib/store/index.ts, packages/core/src/lib/waku.ts, packages/interfaces/src/filter.ts, packages/interfaces/src/message.ts, packages/interfaces/src/protocols.ts, packages/message-encryption/src/ecies.ts, packages/message-encryption/src/symmetric.ts, packages/relay/src/index.ts, packages/sdk/src/create.ts, packages/tests/tests/filter/multiple_pubsub.node.spec.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/light-push/multiple_pubsub.node.spec.ts, packages/tests/tests/light-push/utils.ts, packages/tests/tests/relay/multiple_pubsub.node.spec.ts, packages/tests/tests/store/multiple_pubsub.spec.ts, packages/tests/tests/store/utils.ts, packages/utils/src/common/sharding.spec.ts, packages/utils/src/common/sharding.ts
Named sharding was removed completely and the APIs were changed. If we release a new package, this would break any existing projects that use js-waku. Named sharding should be deprecated, but the constructors/API should be maintained such that any existing projects have time to migrate to static or autosharding.
- Introduce a new SDK function, `createNode`, which only supports static/autosharding.
- For all existing SDK functions, only enforce static or autosharding if `shardInfo` is set in `ProtocolCreateOptions`.
- Deprecate the `pubsubTopics` field in `ProtocolCreateOptions`.
- Add tests to ensure named sharding still works.
- For all protocol and encoder/decoder constructors, use explicit pubsub topic if set (named sharding behavior). Otherwise, set pubsub topics based on shard info. …
=> feat: reintroduce and deprecate named sharding, make autosharding default for all other cases

.github/workflows/playwright.yml, package-lock.json, package.json, packages/browser-tests/package.json
Auto upgrade didn't handle `playwright` due to additional package present in `browser-tests`.
Upgrade manually. 
- Related to https://github.com/waku-org/js-waku/pull/1752
=> chore: upgrade playwright

packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/multiple_pubsub.node.spec.ts, packages/tests/tests/store/multiple_pubsub.spec.ts, packages/utils/src/libp2p/index.ts
Fixes some failing tests in #1756 and stops throwing errors if node is setup to use autosharding
=> fix: allow autosharding nodes to get peers

packages/core/src/lib/base_protocol.ts, packages/core/src/lib/metadata/index.ts, packages/interfaces/src/constants.ts, packages/interfaces/src/message.ts, packages/interfaces/src/protocols.ts, packages/sdk/src/create.ts, packages/sdk/src/relay/index.ts, packages/tests/tests/filter/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/relay/multiple_pubsub.node.spec.ts, packages/tests/tests/sharding/running_nodes.spec.ts, packages/tests/tests/store/multiple_pubsub.spec.ts, packages/utils/src/common/sharding.ts, packages/utils/src/libp2p/index.ts
To setup a node for autosharding, a user needs to explicitly specify both content topics and a cluster id to determine the pubsub topics. According to the [RFC](https://rfc.vac.dev/spec/64/#network-shards), the Waku Network always uses a cluster id of 1.
Makes `clusterId` (and all other fields in `ShardingParams`) optional when user creates a node using the sdk functions, by accepting `Partial<ShardingParams>`.
Each sdk function calls a sharding util function to validated the parameters and replace any missing ones with defaults where possible.
Internally, we mostly use `ShardingParams` where all fields are required.
- Resolves #1776
=> feat: set cluster ID as optional when specifying shard info

.github/workflows/ci.yml, packages/tests/src/lib/service_node.ts, packages/tests/src/run-tests.js, packages/tests/tests/filter/single_node/subscribe.node.spec.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/metadata.spec.ts
- Bump nwaku to 0.24.0
- Update tests because the content topic limit change did not get into 0.24.0 (will be part of 0.25.0 it seems)
- Upgrade failed named sharding tests to use cluster id 0 because if no `--cluster-id` flag is passed to nwaku 0.24.0 it will use 0 by default
- Other small fixes to failing tests
=> test: fix for nwaku 24

.github/workflows/ci.yml
Remove go-waku interop tests from CI based on [discussion](https://github.com/waku-org/pm/pull/113#event-11650239006) and the fact that go-waku interop tests if failing for a long time and taking a lot of time in the CI
=> test: remove go waku tests from ci

.vscode/settings.json
The flag `source.fixAll.eslint` supports new values on new versions of VSCode that seem to slip in automatically.
VSCode true is set to "explicit" since VSCode 1.85.0. It seems boolean values were supported until 1.84.0.
- Reference: https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
- https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own
=> chore: use updated flag values for vscode eslint settings 

packages/core/src/lib/base_protocol.ts, packages/core/src/lib/filter/index.ts, packages/core/src/lib/light_push/index.ts, packages/core/src/lib/metadata/index.ts, packages/core/src/lib/store/index.ts, packages/core/src/lib/wait_for_remote_peer.ts, packages/core/src/lib/waku.ts, packages/interfaces/src/waku.ts, packages/peer-exchange/src/waku_peer_exchange.ts, packages/peer-exchange/src/waku_peer_exchange_discovery.ts, packages/relay/src/index.ts, packages/sdk/src/create.ts, packages/sdk/src/relay/index.ts, packages/tests/tests/connection_manager.spec.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/peer_exchange.node.spec.ts, packages/tests/tests/peer_exchange.optional.spec.ts, packages/tests/tests/sharding/peer_management.spec.ts, packages/tests/tests/sharding/running_nodes.spec.ts, packages/utils/src/common/sharding.ts
The logic surrounding `ShardingParams` is complex because it has to handle three kinds of sharding (named sharding, autosharding, and static sharding). In either case, the end result is a set of pubsub topics stored by core classes. Currently the logic is duplicated across the core classes, and any change to which kinds of sharding are supported or how they're handled may require changes in many places across the codebase.
- Remove sharding logic from `BaseProtocol` and instead accept pubsub topics.
- ~Add pubsub topics as a constructor parameter for each protocol class~
- make pubsub topic required in `BaseProtocol`
- update SDK functions to determine pubsub topics based on `ShardingParams` and pass them on to node being created
- Resolves #1808
=> feat: decouple sharding params out of core

packages/message-encryption/src/index.ts
In some cases export of `./crypto` is braking some build systems.
Make export explicit.
=> chore: fix export of crypto submodule

packages/tests/src/lib/dockerode.ts, packages/tests/src/lib/service_node.ts, packages/tests/src/types.ts, packages/tests/tests/nwaku.node.spec.ts
nwaku will be deprecating JSON RPC API. We will no longer be able to use those endpoints in e2e tests and must switch to using the REST API.
This PR migrates two endpoints used in e2e from RPC to REST: `GET /relay/v1/messages/` and `POST /relay/v1/subscriptions`
Also updates utils for running the Docker image to provide arguments to enable `rest` and run it on `restPort`
- Related to #1826
=> feat: switches to REST for calling nwaku messages/subscription endpoints

packages/tests/src/constants.ts, packages/tests/src/lib/index.ts, packages/tests/src/lib/service_node.ts, packages/tests/src/types.ts, packages/tests/tests/filter/push.node.spec.ts, packages/tests/tests/filter/single_node/push.node.spec.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/nwaku.node.spec.ts
nwaku is deprecating the JSON RPC api for communicating with a node. js-waku uses the api when running e2e tests.
- Replace all use of JSON RPC API with REST API
- Update docker settings to run nwaku in tests with REST enabled
- remove already deprecated endpoints from `/private`
- Resolves #1826
=> feat: migrates e2e tests to use rest instead of rpc

.size-limit.cjs, packages/core/src/index.ts, packages/core/src/lib/wait_for_remote_peer.ts, packages/interfaces/src/protocols.ts, packages/sdk/src/content_topic.ts, packages/sdk/src/create.ts, packages/sdk/src/index.ts, packages/sdk/src/relay/index.ts, packages/sdk/src/waku.ts, packages/tests/tests/sdk/content_topic.spec.ts, packages/tests/tests/waku.node.spec.ts
There is currently no simple way to create a subscription with just a content topic.
Adds SDK functions that given a content topic will create a waku node and a subscription to the provided content topic. It assumes autosharding is being used.
- Related to #1764
=> feat: subscribe to content topic via SDK

packages/tests/src/lib/dockerode.ts, packages/tests/src/lib/service_node.ts, packages/tests/src/types.ts, packages/tests/tests/nwaku.node.spec.ts
Per nwaku team, all rpc flags will no longer exist after v0.26.0 release. Our tests try to start nwaku with those flags passed, and that causes problems when running against newest version.
Remove all rpc flags from Docker args when starting nwaku
- Related to #1826
=> fix: remove rpc settings when starting nwaku image

release-please-config.json
`@waku/local-peer-cache-discovery` wasn't added as a tracked package for release
Add it
=> chore: add local peer discovery package to release tracking

packages/tests/src/lib/service_node.ts, packages/tests/tests/connection-mananger/methods.spec.ts, packages/tests/tests/peer-exchange/query.spec.ts
1. Fix and unskio connectionManager.dispatchEvent according to https://github.com/waku-org/js-waku/issues/1835#issuecomment-1983746362
2. Fix port overflow [error](https://github.com/waku-org/js-waku/actions/runs/8203245030/job/22435659250#step:7:1432)
3. Skipped flaky [test](https://github.com/waku-org/js-waku/actions/runs/8203245030/job/22435659250#step:7:1445) that I just couldn't reliably fix in CI although it works fine locally
=> test: fix dispatchEvent test

packages/tests/tests/getPeers.spec.ts
The tests written to check connection for nodes when the cluster is same, but the shard is different, was expected to have the nodes connect. This worked fine interop until nwaku rc 0.24.0
With the introduction of the metadata protocol, the tests started to fail since this should not be allowed and the actual expectation from the test is that the nodes **should not connect**
- Resolves https://github.com/waku-org/js-waku/issues/1848
=> fix(tests): sharding: same cluster, different shard

package-lock.json, packages/core/package.json, packages/dns-discovery/package.json, packages/enr/package.json, packages/local-peer-cache-discovery/package.json, packages/message-encryption/package.json, packages/message-hash/package.json, packages/peer-exchange/package.json, packages/relay/package.json, packages/sdk/package.json, packages/utils/package.json
Package discrepancy might occur.
More details - https://github.com/waku-org/js-waku/issues/1872
Add `peerDependency` 
- Resolves https://github.com/waku-org/js-waku/issues/1872
=> feat: add cross peer dependency for @waku packages

packages/core/src/lib/light_push/index.ts, packages/discovery/src/peer-exchange/waku_peer_exchange.ts, packages/discovery/src/peer-exchange/waku_peer_exchange_discovery.ts, packages/interfaces/src/metadata.ts, packages/interfaces/src/peer_exchange.ts, packages/interfaces/src/protocols.ts, packages/tests/tests/peer-exchange/query.spec.ts
Protocols currently use different pattern to handle errors: #1694.
- addresses the peer-exchange protocol to use error codes
- introduces a generic that can be reused in each protocol with flexibility (DRY)
- gives a much better error handling since `error` (with `unknown` type) is not thrown, but returned with a predetermined type
- Related to https://github.com/waku-org/js-waku/issues/1694
=> feat: peer-exchange uses error codes

packages/sdk/src/utils/libp2p.ts
When running the js-waku lab examples, accessing `process` directly breaks as the variable is undefined.
Check for `process` and `process.env` not being `undefined`
=> fix: check if process is defined before accessing it

.size-limit.cjs, package-lock.json, package.json, packages/core/package.json, packages/core/src/index.ts, packages/core/src/lib/store/index.ts, packages/core/src/lib/wait_for_remote_peer.ts, packages/interfaces/package.json, packages/interfaces/src/store.ts, packages/interfaces/src/waku.ts, packages/sdk/package.json, packages/sdk/src/index.ts, packages/sdk/src/light-node/index.ts, packages/sdk/src/protocols/store.ts, packages/sdk/src/relay-node/index.ts, packages/sdk/src/waku.ts, packages/tests/tests/store/cursor.node.spec.ts, packages/tests/tests/wait_for_remote_peer.node.spec.ts
#1886 
Moves away the abstraction of using multiple peers, along with the offered APIs to make queries for store by:
- creating a new class `StoreSDK` (and renaming protocol implementation to `StoreCore`
- `StoreCore` contains one API that returns an `AsyncGenerator`: `*queryPerPage`
- `StoreSDK` offers different APIs to query, that uses `queryPerPage`
- Increases readability and modularity
- https://github.com/waku-org/js-waku/issues/1886
=> chore(store)!: move protocol implementation opinions to `@waku/sdk`

package-lock.json, packages/sdk/package.json, packages/sdk/src/utils/discovery.ts
We moved individual discovery packages (`@waku/dns-discovery`, `@waku/peer-exchange`, `@waku/local-peer-cache-discovery`) under one single package: `@waku/discovery`: https://github.com/waku-org/js-waku/pull/1876
Some references in `@waku/sdk` remained
Remove these references
- Related to https://github.com/waku-org/js-waku/pull/1910
=> chore: remove stale references to deprecated packages

package-lock.json, packages/core/src/lib/predefined_bootstrap_nodes.ts, packages/discovery/src/dns/constants.ts, packages/discovery/src/dns/dns.spec.ts, packages/discovery/src/dns/fetch_nodes.spec.ts, packages/enr/src/enr.spec.ts, packages/enr/src/multiaddrs_codec.spec.ts, packages/sdk/src/utils/discovery.ts, packages/tests/tests/dns-peer-discovery.spec.ts, packages/tests/tests/peer-exchange/pe.optional.spec.ts, packages/tests/tests/waku.node.optional.spec.ts
See https://github.com/status-im/infra-nim-waku/issues/91 for details
Mostly done automatically. Some parts manually.
I've added some TODO comments to the addresses, which I don't know how to fix.
=> chore: switch wakuv2 fleet to waku

.release-please-manifest.json
Similarly to https://github.com/waku-org/js-waku/pull/1937 release of `discovery` starts with `1.0.0`.
Force it to start with `0.0.2`.
=> chore: force discovery release version

.release-please-manifest.json
Since `discovery` is consumed and locked to 0.0.1 in other packages and release bot tries to bump it to 0.0.2 - it fails.
We should seed release with 0.0.0 to have 0.0.1 as the first version to be released. According [to docs](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#bootstrapping) it seems the most straightforward way
=> chore: initialize new packages from 0.0.0 version

package-lock.json, packages/discovery/package.json, release-please-config.json
`@waku/discovery` is missing `core` as dependency
`release-please` is not bumping `peer` dependencies
Add dependency
Update config
=> chore: update release-please config and fix missing dependency on discovery

packages/proto/src/generated/store.ts, packages/proto/src/lib/store.proto
Find test failure in nwaku ci:
```
2024-04-09T09:49:52.0513572Z   8) Waku Store, general
2024-04-09T09:49:52.0513871Z        Query generator for 2000 messages:
2024-04-09T09:49:52.0514217Z      Error: Invalid enum value
2024-04-09T09:49:52.0514929Z       at findValue (file:///home/runner/work/nwaku/nwaku/node_modules/protons-runtime/src/codecs/enum.ts:9:13)
2024-04-09T09:49:52.0516150Z       at Object.enumDecode [as decode] (file:///home/runner/work/nwaku/nwaku/node_modules/protons-runtime/src/codecs/enum.ts:24:12)
2024-04-09T09:49:52.0517376Z       at Object.decode (file:///home/runner/work/nwaku/nwaku/packages/proto/src/generated/store.ts:451:64)
2024-04-09T09:49:52.0519087Z       at Object.decode (file:///home/runner/work/nwaku/nwaku/packages/proto/src/generated/store.ts:533:54) …
```
=> fix: Added missing values for HistoryError to be sync with nwaku

.size-limit.cjs, package-lock.json, packages/core/package.json, packages/core/src/index.ts, packages/core/src/lib/filter/index.ts, packages/core/src/lib/wait_for_remote_peer.ts, packages/interfaces/src/filter.ts, packages/interfaces/src/waku.ts, packages/sdk/package.json, packages/sdk/src/index.ts, packages/sdk/src/light-node/index.ts, packages/sdk/src/protocols/base_protocol.ts, packages/sdk/src/protocols/filter.ts, packages/sdk/src/protocols/light_push.ts, packages/sdk/src/relay-node/index.ts, packages/sdk/src/waku.ts, packages/tests/tests/sdk/content_topic.spec.ts, packages/tests/tests/wait_for_remote_peer.node.spec.ts
Part of https://github.com/waku-org/js-waku/issues/1886, the current Filter implementation is quite coupled in terms of the RFC specs + our opinions of using peers, handling subscriptions, etc
Decouple Filter into `SDK` and `Core`
- now that we decoupled the logic, more improvements possible 
- will do more cleanup with a followup PR once this is merged
- sry for the big diff - no way around - tried to keep it minimal 
- Related to #1886 
=> chore(lightpush)!: move protocol implementation to `@waku/sdk` (1/n)

.github/workflows/ci.yml, packages/tests/src/lib/service_node.ts, packages/tests/src/run-tests.js, packages/tests/src/utils/waku_versions_utils.ts, packages/tests/tests/filter/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/filter/single_node/subscribe.node.spec.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/metadata.spec.ts, packages/tests/tests/relay/multiple_pubsub.node.spec.ts, packages/tests/tests/sdk/content_topic.spec.ts, packages/tests/tests/sharding/auto_sharding.spec.ts, packages/tests/tests/sharding/peer_management.spec.ts, packages/tests/tests/sharding/static_sharding.spec.ts, packages/tests/tests/store/multiple_pubsub.spec.ts
Upgrade nwaku to v0.27.0 and adjust the tests to work with this version
=> chore: use nwaku:v0.27.0 and adjust tests for it

packages/proto/src/generated/store.ts, packages/proto/src/lib/store.proto
The error message for too many requests when querying store does not match what is set in nwaku
Update the error message in proto def to match nwaku
=> fix: use correct error message for store rate limit

packages/core/src/lib/message/version_0.spec.ts, packages/interfaces/src/message.ts, packages/utils/src/common/sharding.spec.ts, packages/utils/src/common/sharding.ts
When library consumer specifies a cluster ID and shard index when creating an encoder, it means they are using static sharding and explicitly specifying which shard index (and thus pubsub topic) should be used.
Currently, when an encoder is created this way, it uses the autosharding algorithm to determine the shard index based on content topic, which can lead to unexpected results if it doesn't match the shard index specified by the consumer.
- Make `shard` property optional in `SingleShardInfo`.
- Fix conditional that evaluates to falsy when `shard` is set to `0` (this was preventing static sharding from being used)
- Resolves #1874
=> fix: use correct shard index when creating encoder

packages/tests/tests/sharding/static_sharding.spec.ts
Un-skipping test because [#1874](https://github.com/waku-org/js-waku/issues/1874)  was closed as completed via [#1885](https://github.com/waku-org/js-waku/pull/1885).
=> test: unskip shard 0 test fixed by 1874

packages/tests/tests/peer-exchange/pe.optional.spec.ts
In order for the node to discover and connect to new peers different than the fleets, we should be in `cluster-id` 1 and subscribed to some shard.
This would fix the failing js-optional tests
Advances https://github.com/waku-org/nwaku/issues/2621
=> fix: peer exchange tests

packages/message-hash/src/index.spec.ts, packages/message-hash/src/index.ts, packages/utils/src/bytes/index.ts
Based on the specs: https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/14/message.md#deterministic-message-hashing, the current message-hash algorithm does not take into account the `timestamp`.
The test vectors mentioned in the spec also varied from the one in the implementation.
- Update the algorithm to account for `timestamp`
- Update the test vectors
- Resolves https://github.com/waku-org/js-waku/issues/1985
=> fix(message-hash): account for `timestamp`

packages/interfaces/src/libp2p.ts, packages/sdk/src/utils/libp2p.ts, packages/sdk/src/waku.ts
When a peer is connected to js-waku, it often exceeds the default number of incoming streams for libp2p's ping protocol. This causes the multiplexer to drop the entire connection, effectively losing the peer.
Add an option to overwrite the maximum number of inbound connections for the ping protocol when creating a waku node, and set the default to 10.
- Related to #1966 
=> feat: add libp2p option for max ping connections

packages/core/src/lib/keep_alive_manager.ts, packages/tests/tests/metadata.spec.ts
After pinging a peer, the keep alive manager overwrites _all_ the metadata stored for that peer and replaces it with the latency of the ping. This causes the peer store to lose any other metadata that was stored, including the peer's shard info.
Use `peerStore.merge` instead of `peerStore.patch` to update the metadata, which will only overwrite the last value of `ping` and not wipe the rest of the metadata.
- Related to #1966 
=> fix: only override ping metadata in peer store

packages/message-hash/src/index.spec.ts, packages/message-hash/src/index.ts
It is convenient to use `messageHash` for end users against `DecodedMessage` as it is the version they get from `Filter`.
Make `messageHash` compatible with `IDecodedMessage`
=> feat: make message hash compatible with decoded message

packages/sdk/src/utils/libp2p.ts
Current libp2p transport filter allows all connections. This is fine for testing, but in production we want to limit transports to secure WebSockets (wss or tls/ws).
Allow all transport types when running tests by setting `process.env.NODE_ENV=test` but otherwise use the libp2p filter for secure websockets peers
- Resolves #1547 
- Related to #1966 
=> fix: filter for wss in libp2p websocket transport

packages/tests/src/run-tests.js, packages/tests/src/types.ts, packages/tests/tests/sharding/peer_management.spec.ts
Tests for checking that connection manager dials the correct peers based on sharding params were failing against nwaku
1. Add `NODE_ENV=test` to env vars when running tests
2. Add `shard` argument when starting nwaku
3. Use correct `shard` arguments when running tests in `peer_management.spec.ts`
=> fix: add shard arg to nwaku in peer management tests

.github/workflows/ci.yml, package.json, packages/tests/src/constants.ts, packages/tests/src/lib/dockerode.ts, packages/tests/src/lib/service_node.ts, packages/tests/src/sync-rln-tree.js, packages/tests/src/types.ts
Tests that run against cluster id 1 (The Waku Network) require running an nwaku node with a sepolia RPC url.
When adding this parameter, the nwaku node will not be "ready" (`/health` returns status 200) until the RLN tree is synced. If starting from scratch, this process takes a long time (up to 5 minutes, and will only take longer as more blocks are mined on Sepolia).
Add a step to the CI that:
- checks if the `rln_tree.db` is stored as an artifact. If so, pull it.
- run an nwaku node in docker that mounts the `rln_tree.db` until the `/health` endpoint returns 200 (basically syncs the rln_tree to latest block on sepolia)
- store the synced `rln_tree.db` as an artifact
For now, the step is disabled. When we have tests that run against TWN, we will enable this job and have it be a prereq …
=> feat: add rpc url to nwaku, persist rln tree in docker and ci

package-lock.json, packages/core/package.json, packages/discovery/package.json, packages/enr/package.json, packages/message-encryption/package.json, packages/message-hash/package.json, packages/relay/package.json, packages/sdk/package.json, packages/utils/package.json
In apps and libraries that consume `js-waku` might happen a problem with resolving packages.
Example - https://github.com/waku-org/waku-react/actions/runs/9923111221/job/27412913948?pr=46
Manually bump.
Related to - https://github.com/waku-org/js-waku/issues/2063
=> chore: bump @waku peer dependencies

packages/core/src/index.ts, packages/core/src/lib/base_protocol.ts, packages/core/src/lib/connection_manager.ts, packages/core/src/lib/keep_alive_manager.ts, packages/core/src/lib/stream_manager/index.ts, packages/core/src/lib/stream_manager/stream_manager.ts, packages/core/src/lib/stream_manager/utils.ts, packages/sdk/src/protocols/base_protocol.ts, packages/sdk/src/protocols/filter.ts, packages/utils/src/libp2p/index.ts
Peer renewal doesn't work as intended.
Current behavior - it renews a peer to a one with which light node has a connection already.
Expected behavior - renews to a peer which we don't have a connection. 
This PR also adds decrease for Filter keep alive queries to 30 seconds as was proposed in one of the threads in https://github.com/waku-org/specs/pull/18, and some code improvements. 
Fix the behavior and add some improvements.
Tested in the dogfooding app - https://github.com/waku-org/lab.waku.org/pull/68
=> feat: fix peer renewal, change Filter keep alive

packages/discovery/src/dns/constants.ts, packages/interfaces/src/constants.ts, packages/interfaces/src/protocols.ts, packages/message-encryption/src/symmetric.ts, packages/relay/src/index.ts, packages/relay/src/topic_only_message.ts, packages/sdk/src/create/discovery.ts, packages/sdk/src/create/libp2p.ts, packages/tests/src/constants.ts, packages/tests/src/lib/index.ts, packages/tests/src/lib/message_collector.ts, packages/tests/src/lib/service_node.ts, packages/tests/tests/connection-mananger/connection_state.spec.ts, packages/tests/tests/enr.node.spec.ts, packages/tests/tests/filter/peer_management.spec.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/peer_management.spec.ts, packages/tests/tests/nwaku.node.spec.ts, packages/tests/tests/wait_for_remote_peer.node.spec.ts, packages/tests/tests/waku.node.spec.ts, packages/utils/src/common/sharding.ts
Named sharding is deprecated.
We need to comply
- Keep `pubsubTopic` parameter as a fallback for consumers of the library that do not use The Waku Network or static sharding;
- Provide `DefaultShardInfo` as a fallback that is configured for The Waku Network all shards;
- Remove old `DefaultPubsubTopic`;
- Main PR: https://github.com/waku-org/js-waku/pull/2083/files
- Addresses: https://github.com/waku-org/js-waku/issues/2082
=> feat: create default shard info, update tests

packages/core/CHANGELOG.md, packages/discovery/src/dns/constants.ts, packages/interfaces/src/constants.ts, packages/interfaces/src/protocols.ts, packages/message-encryption/src/symmetric.ts, packages/message-hash/src/index.spec.ts, packages/relay/src/index.ts, packages/relay/src/topic_only_message.ts, packages/sdk/src/create/discovery.ts, packages/sdk/src/create/libp2p.ts, packages/tests/src/constants.ts, packages/tests/src/lib/index.ts, packages/tests/src/lib/message_collector.ts, packages/tests/src/lib/service_node.ts, packages/tests/tests/connection-mananger/connection_state.spec.ts, packages/tests/tests/enr.node.spec.ts, packages/tests/tests/filter/peer_management.spec.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/getPeers.spec.ts, packages/tests/tests/light-push/peer_management.spec.ts, packages/tests/tests/nwaku.node.spec.ts, packages/tests/tests/peer-exchange/compliance.spec.ts, packages/tests/tests/peer-exchange/index.spec.ts, packages/tests/tests/wait_for_remote_peer.node.spec.ts, packages/tests/tests/waku.node.spec.ts, packages/utils/src/common/sharding.ts
After deprecating named sharding in nwaku, the pubsub topic `/waku/2/default-waku/proto` is no longer valid. We are migrating the default to`/waku/2/rs/0/0` for tests and shard info for TWN (see https://github.com/waku-org/js-waku/pull/2085).
Nwaku nodes weren't starting in some interop tests because of being set up with this no longer valid pubsub topic.
Similarly, as metadata protocol was recently activated for cluster 0, updated some tests in which clusters and shards weren't consistent between nodes, which led to disconnections.
Related to https://github.com/waku-org/nwaku/issues/2621
Includes: https://github.com/waku-org/js-waku/pull/2085
=> chore: changing default pubsub topic to its static sharding version

packages/interfaces/src/libp2p.ts, packages/sdk/src/create/libp2p.ts
In https://github.com/waku-org/js-waku/pull/1989 we made it so `fitlerAll` is applied only in tests.
Reasoning for it was that in running dogfooding apps we were seeing a lot of errors and we wanted to prevent light node trying to establish a connection that will definitely fail.
But it prevents local development with js-waku so that locally run nodes or nodes run under IP - are ignored and connection is not established or event attempted.
Add `fitlerMultiaddrs` flag to `libp2p` configuration so that is it is set to `false` - then such behavior is off.
- Example of problem https://discord.com/channels/1110799176264056863/1272550972631158888/1273946249980018768
- Updates to docs: https://github.com/waku-org/docs.waku.org/pull/209
=> chore: enable back filterAll if set by consumer

package-lock.json, packages/sdk/src/protocols/store.ts, packages/utils/src/common/sharding/type_guards.ts
Couple of them:
- import is broken;
- type guard for `networkConfig` is not following defined type;
Fix it
=> fix: import of base_protocol and networkConfig type guard

packages/sdk/src/protocols/base_protocol.ts, packages/tests/src/utils/nodes.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/light-push/index.node.spec.ts
As per RFC protocols should use 2 peers https://github.com/waku-org/specs/blob/master/standards/application/req-res-reliability.md#sending-with-redundancy
But 3 are used
Make them use 2
=> chore: change amount of used peers to 2

packages/sdk/src/protocols/filter.ts
This PR addresses 3 problems:
- When peer is renewed and it was used in filter subscription it is not added into missing messages hash map.
Because of that `this.addHash` fails during processing of incoming messages and that terminates callback's invokation.
- Because of bug introduced for keep alive feature - `pings` are not done properly.
- To be more align with RFC - `DEFAULT_MAX_PINGS` has to be changed to `2`;
Fix bugs, change const.
Related bug: https://github.com/waku-org/js-waku/issues/2120
Validated against: `@waku/sdk@0.0.28-5459f48.0` in dogfooding app
=> fix: filter missing messages

package-lock.json, packages/core/package.json, packages/discovery/package.json, packages/enr/package.json, packages/message-encryption/package.json, packages/message-hash/package.json, packages/relay/package.json, packages/sdk/package.json, packages/utils/package.json
`release-please` does not bump peer dependencies for `@waku/*` packages.
Remove peer dependencies for now before https://github.com/waku-org/js-waku/issues/2063 is done.
=> fix: temporarily remove peer cross dependencies

packages/core/src/lib/connection_manager.ts, packages/discovery/src/dns/constants.ts, packages/discovery/src/dns/dns_discovery.ts, packages/interfaces/src/dns_discovery.ts, packages/sdk/src/create/discovery.ts
When `js-waku` node is bootstrapped with default setting AND broken bootstrap node is used it fails sometimes. 
And in that case application using `js-waku` has bad experience. 
As explained in this comment:
The problem occurs when dns discovery gets us a broken bootstrap node is attempted to be used. 
Increase amount of bootstrap nodes used and at the same time respect our good defaults: 2 filter and light push + 1 store nodes.
Improve dialing as when it fails for bootstrap nodes we should try using others.
- Resolves: https://github.com/waku-org/js-waku/issues/2113
=> fix: improve node bootstrapping

packages/interfaces/src/waku.ts, packages/sdk/src/waku/waku.ts
Previously I met people that requested to expose additional information from `WakuNode` object.
It is also used in dogfooding app and whenever we use it - we need to access through `libp2p`.
Abstract `libp2p` away.
=> feat: expose peerId and protocols from WakuNode

packages/sdk/src/protocols/filter/constants.ts
10 seconds as a ping interval might be an overkill and would flood ping requests from multiple clients.
Change it to 1 min
- Related to https://discord.com/channels/1110799176264056863/1292612132227125430/1295320677385244674
=> chore: change default filter ping interval to 1 min

.github/workflows/ci.yml, karma.conf.cjs
Browser tests in CI are failing due to Chrome sandbox issues in the container environment. The specific error indicates that the sandbox cannot be initialized in the Ubuntu environment:
```
No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor
```
Additionally, Firefox tests were potentially affected by container permission issues due to missing HOME directory configuration.
1. Updated the CI workflow to properly configure the container environment:
- Added HOME environment variable to fix Firefox container permissions
- Using the same container configuration as the successful Playwright tests
2. Modified Karma configuration to use CI-specific Chrome launcher with appropriate sandbox flags:
- Added …
=> fix: CI browser/karma

packages/sdk/src/create/libp2p.ts, packages/sdk/src/env.ts
In some build systems `process` variable is not defined. In those cases it is treated according to `ES6` spec and goes through `TDZ`.
Add `try/catch`. 
Resolves https://github.com/waku-org/js-waku/issues/2208
=> fix: access to process variable

package-lock.json, packages/discovery/package.json, packages/sdk/package.json
`pnpm` gets confused with `peerDependencies` `js-waku` has and misses `@libp2p/bootstrap` package.
This PR removes `peerDependencies` as they are making `pnpm` misbehave with how it resolves dependencies. 
There is no problem with `pnpm` as I see, it's more of a problem with `peerDeps` getting out of sync with other deps while `libp2p` goes through upgrade. 
`@waku/sdk` is published under `0.0.30-1c0c5ee.0` version with this fix. 
As for `peerDependencies` - removing them to prevent any confusion. Let's add them back once requested by consumers. 
- Resolves https://github.com/waku-org/js-waku/issues/2199
=> fix: improve dependencies handling of @libp2p in pnpm

.github/workflows/test-node.yml
The test report jobs in GitHub Actions are incorrectly being grouped under "Playwright tests" in the UI, making it confusing to distinguish between different types of test results.
###Solution
Updated the test reporter name in the GitHub workflow to be more descriptive and prevent incorrect grouping:
```
name: Test Report
uses: dorny/test-reporter@v1
with:
name: Mocha Tests - ${{ inputs.test_type }}  # More specific name
path: 'packages/tests/reports/mocha-*.json'
reporter: mocha-json
fail-on-error: true
```
This change ensures test reports appear under their own "Mocha Tests" category instead of being grouped with Playwright tests.
###Notes
- This is a UI/organization improvement only, no functional changes to test execution or reporting
- Makes it easier to find and distinguish between …
=> fix: job title for test reports CI

.github/workflows/ci.yml, .github/workflows/playwright.yml, packages/browser-tests/package.json, packages/tests/tests/wait_for_remote_peer.node.spec.ts, packages/tests/tests/waku.node.spec.ts
This PR addresses breaking changes in following PRs and makes CI green:
- https://github.com/waku-org/js-waku/pull/2191
- https://github.com/waku-org/js-waku/pull/2193
- https://github.com/waku-org/js-waku/pull/2202
Remove not needed tests, update those that should be kept. 
Some tests may be skipped for now and enabled back in the follow up PR.
---
=> fix: make pipeline succeed

package-lock.json, package.json, packages/proto/src/generated/sds_message.ts, packages/proto/src/lib/sds_message.proto, packages/sds/.eslintrc.cjs, packages/sds/.mocharc.cjs, packages/sds/README.md, packages/sds/package.json, packages/sds/rollup.config.js, packages/sds/src/bloom.ts, packages/sds/src/index.spec.ts, packages/sds/src/index.ts, packages/sds/src/probabilities.ts, packages/sds/tsconfig.dev.json, packages/sds/tsconfig.json, packages/sds/typedoc.json
We aim to build the scalable data sync protocol for the browser as its own package within the js-waku monorepo.
Adds a new package for the browser implementation of scalable data sync.
Ports some of the nim implementation of bloom filter to ts.
Adds protobuf definition for SDS messages.
- Resolves https://github.com/waku-org/js-waku/issues/2225
---
=> feat(sds): create package for sds and add protobuf def

package-lock.json, package.json, packages/tests/src/lib/service_node.ts, packages/tests/tests/nwaku.node.spec.ts
We are in the process of deprecating pubsub-topic param from nim-waku. The pubsub-topic shouldn't be used to start nim-waku and instead, a combination of 1 cluster-id plus n shard should be given. This aims to start using the new added param: shard.
Notice that this PR also suggests to update the lint-staged package so that `npx lint-staged` command works well with the new changes.
=> chore(tests): replace `pubsubTopic` param with `clusterid` plus `shard` to start nwaku

.github/actions/prune-vm/action.yml, .github/workflows/ci.yml, .github/workflows/test-node.yml, ci/mergeAllureResults.cjs, package-lock.json, packages/core/.mocha.reporters.json, packages/core/.mocharc.cjs, packages/discovery/.mocha.reporters.json, packages/discovery/.mocharc.cjs, packages/enr/.mocha.reporters.json, packages/enr/.mocharc.cjs, packages/message-encryption/.mocha.reporters.json, packages/message-encryption/.mocharc.cjs, packages/message-hash/.mocha.reporters.json, packages/message-hash/.mocharc.cjs, packages/relay/.mocha.reporters.json, packages/relay/.mocharc.cjs, packages/sdk/.mocha.reporters.json, packages/sdk/.mocharc.cjs, packages/tests/.mocha.reporters.json, packages/tests/.mocharc.cjs, packages/tests/package.json, packages/tests/src/run-tests.js, packages/utils/.mocha.reporters.json, packages/utils/.mocharc.cjs
=> chore: add back allure

packages/core/src/lib/base_protocol.ts, packages/core/src/lib/filter/filter.ts, packages/core/src/lib/light_push/light_push.ts, packages/core/src/lib/metadata/metadata.ts, packages/core/src/lib/store/store.ts, packages/core/src/lib/stream_manager/stream_manager.spec.ts, packages/core/src/lib/stream_manager/stream_manager.ts, packages/discovery/src/peer-exchange/waku_peer_exchange.ts, packages/sdk/src/filter/filter.ts, packages/sdk/src/filter/subscription_monitor.ts, packages/sdk/src/light_push/light_push.spec.ts, packages/sdk/src/light_push/light_push.ts, packages/sdk/src/peer_manager/peer_manager.spec.ts, packages/sdk/src/peer_manager/peer_manager.ts, packages/sdk/src/store/store.ts
During core protocol operations we often await `peerStore` to get us `Peer` based on `PeerId`.
Upon looking into the code, it appears as unnecessary step. 
Replace that usage.
- Resolves https://github.com/waku-org/js-waku/issues/2232
---
=> feat: move Peer to PeerId

.github/workflows/ci.yml, .github/workflows/test-node.yml, packages/tests/.mocharc.cjs, packages/tests/src/lib/dockerode.ts, packages/tests/src/lib/index.ts, packages/tests/src/lib/service_node.ts, packages/tests/src/run-tests.js, packages/tests/src/sync-rln-tree.js, packages/tests/src/utils/nodes.ts, packages/tests/src/utils/teardown.ts, packages/tests/tests/dns-peer-discovery.spec.ts, packages/tests/tests/ephemeral.node.spec.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/light-push/index.node.spec.ts, packages/tests/tests/light-push/single_node/index.node.spec.ts, packages/tests/tests/light-push/single_node/multiple_pubsub.node.spec.ts, packages/tests/tests/sharding/auto_sharding.spec.ts, packages/tests/tests/sharding/static_sharding.spec.ts, packages/tests/tests/store/index.node.spec.ts, packages/tests/tests/store/multiple_pubsub.spec.ts
This pull request upgrades the nwaku dependency to version `0.34.0` and includes various improvements and fixes in the test suite to accommodate this upgrade. Key changes include:
- Updates to the CI workflow configuration to use the new nwaku version.
- Enhancements and adjustments to the test suite:
- service nodes (nwaku) spawned together connect to each other via Relay 
- adds deduplication logic for ecies encrypted payloads to avoid being considered as multiple messages
- single node lightpush tests now expected to fail (nwaku requires minimum 1 peer part of the mesh)
- Resolves https://github.com/waku-org/js-waku/issues/2176
=> chore: upgrade nwaku to 0.34.0 and update tests suite for compatibility

package-lock.json, package.json
We currently build/run tests on core/functionality packages like RLN and SDS **after** `tests`. We should have tests run mostly at the end, with scope to extend SDS/RLN tests into the `tests` package.
This PR rearranges the monorepo setup to build/test functional packages like RLN and SDS before the tests suite package.
---
=> chore: sds and rln before tests

packages/interfaces/src/protocols.ts, packages/sdk/src/create/create.ts, packages/sdk/src/waku/waku.ts
Developers need to explicitly call `node.start` but can forget to do so sometimes. 
Add `autoStart` option.
- Resolves https://github.com/waku-org/js-waku/issues/2290
---
N/A
=> feat: enable auto start upon node creation

packages/sds/src/sds.spec.ts, packages/sds/src/sds.ts
Per https://rfc.vac.dev/vac/raw/sds/#periodic-incoming-buffer-sweep :
> Periodic Incoming Buffer Sweep
> The participant MUST periodically check causal dependencies for each message in the incoming buffer. For each message in the incoming buffer:
> 
> the participant MAY attempt to retrieve missing dependencies from the Store node (high-availability cache) or other peers.
> if all dependencies of a message are met, the participant MUST proceed to [deliver the message](https://rfc.vac.dev/vac/raw/sds/#deliver-message).
> If a message's causal dependencies have failed to be met after a predetermined amount of time, the participant MAY mark them as irretrievably lost.
> 
> Periodic Outgoing Buffer Sweep
> The participant MUST rebroadcast unacknowledged outgoing messages after a set period. …
=> feat(sds): adds logic to sweep incoming and outgoing buffers

packages/sds/src/sds.spec.ts, packages/sds/src/sds.ts
Per the [specifications](https://rfc.vac.dev/vac/raw/sds/#periodic-sync-message), participants should periodically send sync messages. These are sent with empty content and should not be persisted.
Adds a public function for sending a sync message in the channel.
Updates other functions to properly handle sync messages (e.g. received messages that are determined to be sync messages are not persisited)
- Resolves #2275 
---
=> feat(sds): send and receive sync messages

CONTRIBUTING.md, package-lock.json, packages/discovery/package.json, packages/discovery/src/dns/dns_over_https.ts, packages/tests/tests/waku.node.optional.spec.ts
XMLHttpRequest is a deprecated API and not available in browser extension.
Remove dependency that uses XMLHttpRequest, for a modern one that uses fetch API
The resulting changes are less configurable (removed option to set retries and DNS-over-HTTP servers). I am assuming no one uses those options.
If someone does, it is pretty easy to re-add them.
=> doc: build first to avoid not found deps issues

.github/actions/npm/action.yml
`npm i` custom command fails to resolve dependencies on releases
It seems some changes were done to Github context and `ref` cannot be used for detecting branch names. 
- Resolves https://github.com/waku-org/js-waku/issues/2296
- Related to https://github.com/waku-org/js-waku/pull/2304
---
=> fix: npm action branch detection

.github/workflows/ci.yml, .release-please-manifest.json, packages/rln/package.json, release-please-config.json
1. `release-please` got updated 
2. new `sds` and `rln` packages were not added into the release please hence their deps were not bumped leading to issues https://github.com/waku-org/js-waku/actions/runs/13945155395/job/39030577038?pr=2309
1. Upgrade release please
2. Add new packages for tracking
- Resolves https://github.com/waku-org/js-waku/issues/2063 and https://github.com/waku-org/js-waku/issues/2296
=> chore: up release-please

packages/sdk/src/create/discovery.ts, packages/tests/tests/waku.node.optional.spec.ts
The waku test fleet is unstable and should not be used as boostrap.
The issue is that DNS Discovery looks for "2" nodes and stop there. Meaning that if those "discovered" nodes are not reachable (ie, coming from test suite). js-waku does not connect.
Only use waku sandbox as default boostrap\
- Resolves
- Related to
---
=> fix: do not use waku test fleet as default bootstrap

packages/tests/src/utils/nodes.ts, packages/tests/tests/light-push/index.node.spec.ts
`nwaku` has a bug that makes one test case flaky
https://github.com/waku-org/nwaku/issues/3369
Skip the test and make a blocking task on js-waku side.
- Related to https://github.com/waku-org/js-waku/issues/2176
=> chore: skip flaky test due to nwaku bug

packages/core/src/lib/message/version_0.ts, packages/interfaces/src/constants.ts, packages/interfaces/src/waku.ts, packages/sdk/src/waku/utils.spec.ts, packages/sdk/src/waku/utils.ts, packages/sdk/src/waku/waku.ts, packages/tests/tests/filter/subscribe.node.spec.ts, packages/tests/tests/filter/utils.ts, packages/tests/tests/light-push/index.node.spec.ts, packages/tests/tests/light-push/utils.ts
It is easy to make a mistake when creating Decoder or Encoder as network configuration can be missed or provided wrong. 
Also, it makes not much sense to re-specify it when it is already known to the node.
Provides following API:
```typescript
const node = createLightNode({ defaultBootstrap: true });
const encoder = node.createEncoder({ ... }); // <- potentially by using some params asym/sym encoder/decoder can be instantiated
const decoder = node.createDecoder({ ... });
```
This should improve creation process and rely on already present info of the network config easing life for consumers who run on different shards other than default.
- Resolves https://github.com/waku-org/js-waku/issues/2297
---
- ~[ ] A **test version has been published**, if required.~
=> feat: introduce `createDecoder` and `createEncoder` on `IWaku`

packages/sdk/src/health_indicator/health_indicator.spec.ts, packages/sdk/src/health_indicator/health_indicator.ts
`HealthIndicator` was using `peer:connect` to identify presence of peers and map their protocols.
Unfortunately it seems that when `peer:connect` is fired, the peer is not yet was identified. 
Due to that we need to use `peer:identify` event.
User `peer:identify` event.
- Resolves https://github.com/waku-org/js-waku/issues/2327
---
- ~[ ] A **test version has been published**, if required.~
=> fix: health indicator properly handle peer:identify event

packages/sds/package.json, packages/sds/src/sds.spec.ts, packages/sds/src/sds.ts
Per the [spec](https://rfc.vac.dev/vac/raw/sds/#ephemeral-messages), SDS optionally supports ephemeral messages. These are messages that do not have the same persistence/reliability requirements as regular messages, and effectively skip the buffers.
Part of the requirement is that they are delivered right away upon receipt, which revealed that there's currently no way to notify the library consumer when a message reaches the delivered state.
Add a function for sending ephemeral messages.
Add an optional callback for delivered messages that is called whenever a message reaches that state.
Use libp2p event emitter to emit an event with the message ID when a message is delivered.
The number of optional arguments in the class constructor was getting large so I replaced it with a single …
=> feat(sds): adds ephemeral messages, delivered message callback and event

packages/core/src/lib/connection_manager/connection_manager.spec.ts, packages/core/src/lib/connection_manager/connection_manager.ts, packages/core/src/lib/metadata/metadata.ts, packages/interfaces/src/connection_manager.ts, packages/interfaces/src/metadata.ts, packages/interfaces/src/sharding.ts, packages/relay/src/create.ts, packages/sdk/src/create/create.ts, packages/sdk/src/create/libp2p.ts, packages/sdk/src/filter/filter.spec.ts, packages/sdk/src/filter/filter.ts, packages/sdk/src/filter/types.ts, packages/sdk/src/light_push/light_push.spec.ts, packages/sdk/src/light_push/light_push.ts, packages/sdk/src/store/store.ts, packages/sdk/src/waku/waku.ts, packages/tests/tests/connection-mananger/network_monitor.spec.ts, packages/tests/tests/sharding/auto_sharding.spec.ts, packages/tests/tests/sharding/static_sharding.spec.ts, packages/tests/tests/store/error_handling.node.spec.ts
For an edge node, there is no such thing as a "pubsub topic configuration". An edge node should be able to operate for any possible shard, and it is a per-protocol matter (eg send message with light push).
A relay node does subscribe to shards, but in this case, even metadata protocol does not need to advertise them, this is already handled by gossipsub.
Only service node should advertise their shards via metadata protocol, which is out of scope for js-waku.
- remove `pubsubTopic` configuration at node creation (aligned with Waku API spec proposal https://github.com/waku-org/specs/pull/65 )
- do not send shards in waku metadata messages
- Works toward resolving configuration of nwaku nodes in test by removing mandatory pubsub topic value as a first step
- Next step is to properly separate …
=> fix!: remove node level pubsub topic concept

packages/sds/src/bloom_filter/bloom.ts, packages/sds/src/message_channel/events.spec.ts
Bloom filters cannot be used once decoded from protobuf.
This is because the `UInt8Array` passed is coming from the whole protobuf decoding, ie, with more bytes than just the bloom filter.
Which is why, it is important to always use the offset and length when using the buffer of a byte array.
This is to ensure the right bytes are used to re-build the bloom filter.
It took me many hours to find the culprit
Resolves https://github.com/waku-org/js-waku/issues/2385
---
=> fix: bloom filter protobuf decoding

packages/sds/src/message_channel/events.ts, packages/sds/src/message_channel/message_channel.spec.ts, packages/sds/src/message_channel/message_channel.ts
In the SDS implementation, all messages received are used for acknowledgement purposes.
Including messages that were sent by the local node.
In the context of Waku, one cannot assume their nodes only received messages from other nodes.
Track messages that were sent by the local node, and discard them for acknowledgement purposes.\
Long term solution is to introduced a `senderId` in SDS. This can be tracked another PR for spec and code.
This present solution helps moving the needle to something usable.
---
=> fix: should not self-acknowledge messages

.cspell.json, packages/proto/src/generated/sds_message.ts, packages/proto/src/lib/sds_message.proto, packages/sds/src/index.ts, packages/sds/src/message_channel/events.spec.ts, packages/sds/src/message_channel/events.ts, packages/sds/src/message_channel/message_channel.spec.ts, packages/sds/src/message_channel/message_channel.ts
Proceed with a number of improvements and fixes as I dogfed it and attempted to wrap it.
I want to reach further maturity with the wrapper before pushing it. Those improvements are good on their own.
- implemented `senderId` as per new spec PR https://github.com/vacp2p/rfc-index/pull/170
- move `Message` to a class for easier access to `encode` and decode` methods
- tidy up the event names, to make it clearer whereas they are about incoming or outgoing messages (as some terms of the spec such as "delivered" can be confusing)
- move away from `sendMessage` and `receiveMessage` verbs are nothing is being sent or received. It is instead, push to SDS to be sent by another component.
- improve variable names: `acknowledgements` is about *possible* acks. Also, specs uses *possible* term, not …
=> feat!: SDS improvements and fixes

packages/sdk/src/health_indicator/health_indicator.spec.ts, packages/sdk/src/health_indicator/health_indicator.ts
More event emission than necessary, making it flickered when rendered on a UI.
Only emit when value changes.
- Resolves #2553 
- Related to
---
=> fix: reduce emission of health events

packages/sdk/src/health_indicator/health_indicator.spec.ts, packages/sdk/src/health_indicator/health_indicator.ts, packages/sds/src/bloom_filter/bloom.spec.ts
Health indicator has difficult logic to comprehend leading to bugs being easily introduced.
Make clear re-calculation of health state on every event.
- Resolves https://github.com/waku-org/js-waku/issues/2569
=> fix: make health events emission consistent

packages/rln/src/codec.ts, packages/rln/src/contract/rln_base_contract.ts, packages/rln/src/contract/rln_contract.ts, packages/rln/src/credentials_manager.ts, packages/rln/src/keystore/keystore.ts, packages/rln/src/rln.ts, packages/rln/src/utils/epoch.ts, packages/sdk/src/waku/waku.ts, packages/sds/src/message_channel/message_channel.ts
Logs were marked as `waku:waku`
Remove redundant prefix
---
=> chore: redundant `waku` prefix in logs

packages/sdk/src/filter/filter.spec.ts, packages/sds/src/index.ts, packages/sds/src/message_channel/mem_local_history.ts, packages/sds/src/message_channel/message.spec.ts, packages/sds/src/message_channel/message_channel.spec.ts, packages/sds/src/message_channel/message_channel.ts
Incoming messages did not have retrieval hints when included in causal history for follow-up outbound messages.
This is fix by calculating their retrieval hint upon reception, and before storage.
---
=> fix: (sds) ensure incoming messages have their retrieval hint stored
